$axure.loadCurrentPage({
  "url":"技能.html",
  "generationDate":new Date(1491376838242),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"opentype"],
  "page":{
    "packageId":"cbe1d6ad816340ceae766d0d8c1f32ce",
    "type":"Axure:Page",
    "name":"技能",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"48457416e7b343baa58c167b1bf1b71c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":20,
              "y":25},
            "size":{
              "width":734,
              "height":1295}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c750e31ca57d44738bf6073b7c522a98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":20,
                  "y":25},
                "size":{
                  "width":734,
                  "height":1295}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u0.png"}},
{
          "id":"77714728d6c44a94913070d1b483b648",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":27,
              "y":33},
            "size":{
              "width":720,
              "height":1280}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e63b36bba8040fa8a3e154b3d1a8e38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":27,
                  "y":33},
                "size":{
                  "width":720,
                  "height":1280}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主角（暂停使用）/u2.png"}},
{
          "id":"5c0ccc5630cf44e8b8c45b7173cfe83a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":44,
              "y":100},
            "size":{
              "width":680,
              "height":1190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6b9118da4ab483c84a1df99e1f8a3c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":44,
                  "y":100},
                "size":{
                  "width":680,
                  "height":1190}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主角（暂停使用）/u4.png"}},
{
          "id":"0dec3bdd90c74960be3b866f9196e9f9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":645,
              "y":42},
            "size":{
              "width":102,
              "height":98}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c84157ffe6f149f5ab3912ad5b67c1bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":645,
                  "y":42},
                "size":{
                  "width":102,
                  "height":98}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主界面",
                      "target":{
                        "targetType":"page",
                        "url":"主界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/副本/u50.png"}},
{
          "id":"cff234179c0742b796b00327523f24e6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":66,
              "y":150},
            "size":{
              "width":635,
              "height":99}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a99bfcf85bb492ebb1fba7125a6989e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":66,
                  "y":150},
                "size":{
                  "width":635,
                  "height":99}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技能/u8.png"}},
{
          "id":"e5453a71c36146ad9c371b5c326d1b11",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":99,
              "y":171},
            "size":{
              "width":113,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"330e7a3e2a5f4329833bc2dba98e0094",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":99,
                  "y":171},
                "size":{
                  "width":113,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c00bfc90ccf444c7a6533b9b60f0aed6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFF00,
              "opacity":1},
            "location":{
              "x":296,
              "y":171},
            "size":{
              "width":49,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc0e741e59f1402a85480877664e5baa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF00,
                  "opacity":1},
                "location":{
                  "x":296,
                  "y":171},
                "size":{
                  "width":49,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb4978926c1e47b48704b7ae01e59800",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":534,
              "y":164},
            "size":{
              "width":156,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32cff52a26c14862a29368a3b6364102",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":534,
                  "y":164},
                "size":{
                  "width":156,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"32e603e4ac4240b6bbc398ac9a9e2767",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":66,
              "y":259},
            "size":{
              "width":635,
              "height":896}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"997d0217f8f7496ca8c9c3d51bec0ed6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":66,
                  "y":259},
                "size":{
                  "width":635,
                  "height":896}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技能/u16.png"}},
{
          "id":"dcf1c3d37c514939908af87287005843",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":160,
              "y":1170},
            "size":{
              "width":201,
              "height":91}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7af63a8e8c584fa5a2e934502cdb2a9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":160,
                  "y":1170},
                "size":{
                  "width":201,
                  "height":91}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"fc39b97cbcb94045b894dbc02c4d57df",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":400,
              "y":1170},
            "size":{
              "width":201,
              "height":91}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f14d14a0dcb477ca043389606646377",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":400,
                  "y":1170},
                "size":{
                  "width":201,
                  "height":91}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"a2dfe58e824a4793a2436d998d2ea55c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":90,
              "y":267},
            "size":{
              "width":587,
              "height":290}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"294031c95d2343c1a34c0d444e7151d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":90,
                  "y":267},
                "size":{
                  "width":587,
                  "height":290}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技能/u22.png"}},
{
          "id":"55e339e2066d4920a3c9e344317a582e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":458,
              "y":476},
            "size":{
              "width":187,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cffa8a285b1458e90205f637641b461",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":458,
                  "y":476},
                "size":{
                  "width":187,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"71dc685936384eb48f43d913296176c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":261,
              "y":282},
            "size":{
              "width":88,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4b16d1b0d22424db1849e79c7e00bf4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":261,
                  "y":282},
                "size":{
                  "width":88,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b66bf2ff34b34bafa43fa5af1058ee1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":254,
              "y":345},
            "size":{
              "width":402,
              "height":111}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbeb7eec51954d5b8951181e9b2fb875",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":254,
                  "y":345},
                "size":{
                  "width":402,
                  "height":111}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"121a17b240164166898a7dae08b59c78",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":328},
            "size":{
              "width":390,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/技能/u30_line.png"}},
{
          "id":"1101758e6cd04a9a9f05fbc91b21034f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "opacity":"0.5",
            "location":{
              "x":105,
              "y":301},
            "size":{
              "width":128,
              "height":128}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba4f211174d4439baa69096598b7d1c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "opacity":"0.5",
                "location":{
                  "x":105,
                  "y":301},
                "size":{
                  "width":128,
                  "height":128}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主角（暂停使用）/u14.png"}},
{
          "id":"4f18e35f22014d9fb7c975bb4e2e873d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":552,
              "y":282},
            "size":{
              "width":98,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff1d1cc644cf4a20bece9401df46f9bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":552,
                  "y":282},
                "size":{
                  "width":98,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"94064cd67a694582a5021f55b4a21eb9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":99,
              "y":456},
            "size":{
              "width":557,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/技能/u35_line.png"}},
{
          "id":"f6bfa010cc164ce398b178c42b8bcc67",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":125,
              "y":474},
            "size":{
              "width":333,
              "height":68}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6806580af1104f57af8efcdc74748adb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":125,
                  "y":474},
                "size":{
                  "width":333,
                  "height":68}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"755574e356eb4152bdfe98ccab8e80fa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":90,
              "y":564},
            "size":{
              "width":587,
              "height":290}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98385ce18f6f4e779a4baf321b2d525f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":90,
                  "y":564},
                "size":{
                  "width":587,
                  "height":290}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技能/u22.png"}},
{
          "id":"85f786396a924e56b7ef25b15e20aab7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":458,
              "y":773},
            "size":{
              "width":187,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2476b5d39e3b45f09953e4829e65ef31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":458,
                  "y":773},
                "size":{
                  "width":187,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"ab565652e92f48a7a06a35bb560c41da",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":261,
              "y":579},
            "size":{
              "width":88,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"805dede3773742ffae97e1fed445e7f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":261,
                  "y":579},
                "size":{
                  "width":88,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"47cd0e1ae78e40799c8fb3f606902906",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":254,
              "y":642},
            "size":{
              "width":402,
              "height":111}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f6ba0ea1dad4758a554598bd30e2707",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":254,
                  "y":642},
                "size":{
                  "width":402,
                  "height":111}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab12fd7d9f81447ab0385dfacb977620",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":625},
            "size":{
              "width":390,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/技能/u30_line.png"}},
{
          "id":"87ea70344cef40498ea14c734c62a973",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "opacity":"0.5",
            "location":{
              "x":105,
              "y":598},
            "size":{
              "width":128,
              "height":128}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c63f1c9140a24d448eb16640c56d0005",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "opacity":"0.5",
                "location":{
                  "x":105,
                  "y":598},
                "size":{
                  "width":128,
                  "height":128}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主角（暂停使用）/u14.png"}},
{
          "id":"81519b8fef724e1fa0b21a09fd1f2d25",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":552,
              "y":579},
            "size":{
              "width":98,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9fe731f88f8401f8c7d6bec0fbc87df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":552,
                  "y":579},
                "size":{
                  "width":98,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"67106c7dcf7c4158a65568b426c57390",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":99,
              "y":753},
            "size":{
              "width":557,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/技能/u35_line.png"}},
{
          "id":"4af95bab4cd44a64888e7f395eb59623",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":125,
              "y":771},
            "size":{
              "width":333,
              "height":68}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05dd1c14c23d47b5b86ea40a03edcd5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":125,
                  "y":771},
                "size":{
                  "width":333,
                  "height":68}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b0d1c7b8a7f41c9a4aefa9a305d3b2e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":88,
              "y":858},
            "size":{
              "width":587,
              "height":290}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2bf5366897f4dcf8e049c0e5a7bbbf3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":88,
                  "y":858},
                "size":{
                  "width":587,
                  "height":290}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技能/u22.png"}},
{
          "id":"fe87f4315cc2409fa89c33f1f62c2b49",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":456,
              "y":1067},
            "size":{
              "width":187,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd8b07f0f058424b9b60806610b79370",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":456,
                  "y":1067},
                "size":{
                  "width":187,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"a69201cce88b4c6cb887762bc4af29c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":259,
              "y":873},
            "size":{
              "width":88,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26a0e0596f55419dbdc219acf8a20c90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":259,
                  "y":873},
                "size":{
                  "width":88,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b97518b56b0c4ed48719920f437d1f6f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":252,
              "y":936},
            "size":{
              "width":402,
              "height":111}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f0fb02aad20452b8478c902a46bf923",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":252,
                  "y":936},
                "size":{
                  "width":402,
                  "height":111}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f8bfce5a0114409aa6c69d46d3c911e7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":258,
              "y":919},
            "size":{
              "width":390,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/技能/u30_line.png"}},
{
          "id":"f106ac5fd9924bc18ff8f207547fff9c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "opacity":"0.5",
            "location":{
              "x":103,
              "y":892},
            "size":{
              "width":128,
              "height":128}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b10689b1d1954d39966f4ede6a573574",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "opacity":"0.5",
                "location":{
                  "x":103,
                  "y":892},
                "size":{
                  "width":128,
                  "height":128}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主角（暂停使用）/u14.png"}},
{
          "id":"8e3bf7f5b507448298ea50d25764b47e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":550,
              "y":873},
            "size":{
              "width":98,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ad30042b34d4d0b9cab105534842c3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":550,
                  "y":873},
                "size":{
                  "width":98,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"18800ff9971343c5b29d39a0e62a35ff",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":97,
              "y":1047},
            "size":{
              "width":557,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/技能/u35_line.png"}},
{
          "id":"373a8301a53e4675821df776edaf0b39",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":123,
              "y":1065},
            "size":{
              "width":333,
              "height":68}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a254a00170241ba857d7601c79ff984",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":123,
                  "y":1065},
                "size":{
                  "width":333,
                  "height":68}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "48457416e7b343baa58c167b1bf1b71c":{
      "scriptId":"u0"},
    "c750e31ca57d44738bf6073b7c522a98":{
      "scriptId":"u1"},
    "77714728d6c44a94913070d1b483b648":{
      "scriptId":"u2"},
    "1e63b36bba8040fa8a3e154b3d1a8e38":{
      "scriptId":"u3"},
    "5c0ccc5630cf44e8b8c45b7173cfe83a":{
      "scriptId":"u4"},
    "a6b9118da4ab483c84a1df99e1f8a3c1":{
      "scriptId":"u5"},
    "0dec3bdd90c74960be3b866f9196e9f9":{
      "scriptId":"u6"},
    "c84157ffe6f149f5ab3912ad5b67c1bd":{
      "scriptId":"u7"},
    "cff234179c0742b796b00327523f24e6":{
      "scriptId":"u8"},
    "2a99bfcf85bb492ebb1fba7125a6989e":{
      "scriptId":"u9"},
    "e5453a71c36146ad9c371b5c326d1b11":{
      "scriptId":"u10"},
    "330e7a3e2a5f4329833bc2dba98e0094":{
      "scriptId":"u11"},
    "c00bfc90ccf444c7a6533b9b60f0aed6":{
      "scriptId":"u12"},
    "fc0e741e59f1402a85480877664e5baa":{
      "scriptId":"u13"},
    "eb4978926c1e47b48704b7ae01e59800":{
      "scriptId":"u14"},
    "32cff52a26c14862a29368a3b6364102":{
      "scriptId":"u15"},
    "32e603e4ac4240b6bbc398ac9a9e2767":{
      "scriptId":"u16"},
    "997d0217f8f7496ca8c9c3d51bec0ed6":{
      "scriptId":"u17"},
    "dcf1c3d37c514939908af87287005843":{
      "scriptId":"u18"},
    "7af63a8e8c584fa5a2e934502cdb2a9b":{
      "scriptId":"u19"},
    "fc39b97cbcb94045b894dbc02c4d57df":{
      "scriptId":"u20"},
    "7f14d14a0dcb477ca043389606646377":{
      "scriptId":"u21"},
    "a2dfe58e824a4793a2436d998d2ea55c":{
      "scriptId":"u22"},
    "294031c95d2343c1a34c0d444e7151d6":{
      "scriptId":"u23"},
    "55e339e2066d4920a3c9e344317a582e":{
      "scriptId":"u24"},
    "6cffa8a285b1458e90205f637641b461":{
      "scriptId":"u25"},
    "71dc685936384eb48f43d913296176c2":{
      "scriptId":"u26"},
    "b4b16d1b0d22424db1849e79c7e00bf4":{
      "scriptId":"u27"},
    "b66bf2ff34b34bafa43fa5af1058ee1e":{
      "scriptId":"u28"},
    "fbeb7eec51954d5b8951181e9b2fb875":{
      "scriptId":"u29"},
    "121a17b240164166898a7dae08b59c78":{
      "scriptId":"u30"},
    "1101758e6cd04a9a9f05fbc91b21034f":{
      "scriptId":"u31"},
    "ba4f211174d4439baa69096598b7d1c2":{
      "scriptId":"u32"},
    "4f18e35f22014d9fb7c975bb4e2e873d":{
      "scriptId":"u33"},
    "ff1d1cc644cf4a20bece9401df46f9bc":{
      "scriptId":"u34"},
    "94064cd67a694582a5021f55b4a21eb9":{
      "scriptId":"u35"},
    "f6bfa010cc164ce398b178c42b8bcc67":{
      "scriptId":"u36"},
    "6806580af1104f57af8efcdc74748adb":{
      "scriptId":"u37"},
    "755574e356eb4152bdfe98ccab8e80fa":{
      "scriptId":"u38"},
    "98385ce18f6f4e779a4baf321b2d525f":{
      "scriptId":"u39"},
    "85f786396a924e56b7ef25b15e20aab7":{
      "scriptId":"u40"},
    "2476b5d39e3b45f09953e4829e65ef31":{
      "scriptId":"u41"},
    "ab565652e92f48a7a06a35bb560c41da":{
      "scriptId":"u42"},
    "805dede3773742ffae97e1fed445e7f7":{
      "scriptId":"u43"},
    "47cd0e1ae78e40799c8fb3f606902906":{
      "scriptId":"u44"},
    "7f6ba0ea1dad4758a554598bd30e2707":{
      "scriptId":"u45"},
    "ab12fd7d9f81447ab0385dfacb977620":{
      "scriptId":"u46"},
    "87ea70344cef40498ea14c734c62a973":{
      "scriptId":"u47"},
    "c63f1c9140a24d448eb16640c56d0005":{
      "scriptId":"u48"},
    "81519b8fef724e1fa0b21a09fd1f2d25":{
      "scriptId":"u49"},
    "e9fe731f88f8401f8c7d6bec0fbc87df":{
      "scriptId":"u50"},
    "67106c7dcf7c4158a65568b426c57390":{
      "scriptId":"u51"},
    "4af95bab4cd44a64888e7f395eb59623":{
      "scriptId":"u52"},
    "05dd1c14c23d47b5b86ea40a03edcd5c":{
      "scriptId":"u53"},
    "2b0d1c7b8a7f41c9a4aefa9a305d3b2e":{
      "scriptId":"u54"},
    "b2bf5366897f4dcf8e049c0e5a7bbbf3":{
      "scriptId":"u55"},
    "fe87f4315cc2409fa89c33f1f62c2b49":{
      "scriptId":"u56"},
    "dd8b07f0f058424b9b60806610b79370":{
      "scriptId":"u57"},
    "a69201cce88b4c6cb887762bc4af29c2":{
      "scriptId":"u58"},
    "26a0e0596f55419dbdc219acf8a20c90":{
      "scriptId":"u59"},
    "b97518b56b0c4ed48719920f437d1f6f":{
      "scriptId":"u60"},
    "9f0fb02aad20452b8478c902a46bf923":{
      "scriptId":"u61"},
    "f8bfce5a0114409aa6c69d46d3c911e7":{
      "scriptId":"u62"},
    "f106ac5fd9924bc18ff8f207547fff9c":{
      "scriptId":"u63"},
    "b10689b1d1954d39966f4ede6a573574":{
      "scriptId":"u64"},
    "8e3bf7f5b507448298ea50d25764b47e":{
      "scriptId":"u65"},
    "7ad30042b34d4d0b9cab105534842c3b":{
      "scriptId":"u66"},
    "18800ff9971343c5b29d39a0e62a35ff":{
      "scriptId":"u67"},
    "373a8301a53e4675821df776edaf0b39":{
      "scriptId":"u68"},
    "9a254a00170241ba857d7601c79ff984":{
      "scriptId":"u69"}}});