$axure.loadCurrentPage({
  "url":"药品.html",
  "generationDate":new Date(1491376842568.25),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"opentype"],
  "page":{
    "packageId":"58c9043831174239abaa8467913eade4",
    "type":"Axure:Page",
    "name":"药品",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"aee9a39dff414dac92cb6f314479dfec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":20,
              "y":35},
            "size":{
              "width":734,
              "height":1295}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0749b93143744cdfa3d378e277a17b62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":20,
                  "y":35},
                "size":{
                  "width":734,
                  "height":1295}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u0.png"}},
{
          "id":"ce40f3fd2d8a4cc382f14c93d741e731",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":27,
              "y":43},
            "size":{
              "width":720,
              "height":1280}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"540ad177143a4f689d11e7a27bf0b887",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":27,
                  "y":43},
                "size":{
                  "width":720,
                  "height":1280}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主角（暂停使用）/u2.png"}},
{
          "id":"ca05e1de32f04f1793cbf90001deed61",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":44,
              "y":105},
            "size":{
              "width":680,
              "height":1190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e327bf63daf94ac9a579d5c42ab98519",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":44,
                  "y":105},
                "size":{
                  "width":680,
                  "height":1190}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主角（暂停使用）/u4.png"}},
{
          "id":"858abfe2560f4e82b95c29a6841800b6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":645,
              "y":47},
            "size":{
              "width":102,
              "height":98}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49b7b2a51c354cb48faabf10542eaefe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":645,
                  "y":47},
                "size":{
                  "width":102,
                  "height":98}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主界面",
                      "target":{
                        "targetType":"page",
                        "url":"主界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/副本/u50.png"}},
{
          "id":"2711342c5180499995a2184dc2b8d754",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":64,
              "y":1130},
            "size":{
              "width":636,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/付费/u18_line.png"}},
{
          "id":"4221d184b638443d9f072ad65f4ce7e5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":68,
              "y":910},
            "size":{
              "width":635,
              "height":359}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29affc9e389d42c9a2fac89da45c9625",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":68,
                  "y":910},
                "size":{
                  "width":635,
                  "height":359}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药品/u9.png"}},
{
          "id":"1ad79e2cccc44bc68aceb6ad591fb132",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":68,
              "y":155},
            "size":{
              "width":635,
              "height":725}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"849f63b671ba4ffba11eebf6845fd8bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":68,
                  "y":155},
                "size":{
                  "width":635,
                  "height":725}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药品/u11.png"}},
{
          "id":"ad73b02a9d5b4ee1962c67b2e3a82a72",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "opacity":"0.5",
            "location":{
              "x":88,
              "y":616},
            "size":{
              "width":589,
              "height":149}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e5dcdaa59764b658fd19c98c13b64a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "opacity":"0.5",
                "location":{
                  "x":88,
                  "y":616},
                "size":{
                  "width":589,
                  "height":149}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药品/u13.png"}},
{
          "id":"e6fff608ad0947ebbdeb09b36af0f8b7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":88,
              "y":600},
            "size":{
              "width":160,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a96670bcffe4daab28ba1a4b6f0ed53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":88,
                  "y":600},
                "size":{
                  "width":160,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药品/u15.png"}},
{
          "id":"fd7724ac30af4b7b91c0ae278fbfc21e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":100,
              "y":662},
            "size":{
              "width":560,
              "height":85}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ea408e8cc4a44029af2efc3a22b8b04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":100,
                  "y":662},
                "size":{
                  "width":560,
                  "height":85}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8bb89f96edd54a9bbab7e0bc58d4c7df",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":384,
              "y":775},
            "size":{
              "width":276,
              "height":83}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24f9312cab4349e78f6ff2a23e6ffeeb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":384,
                  "y":775},
                "size":{
                  "width":276,
                  "height":83}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"67c1ec8679ee4deba30465f089f1c361",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":234,
              "y":383},
            "size":{
              "width":114,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/药品/u21_line.png"}},
{
          "id":"81249983357943f8b7bee54b3c4b88ce",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":239},
            "size":{
              "width":48,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/药品/u22_line.png"}},
{
          "id":"c4ba490c8bab455b92ec957f7d45bf07",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":527},
            "size":{
              "width":48,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/药品/u22_line.png"}},
{
          "id":"ab350897e95b4fb3985b1006f7489c1b",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":239},
            "size":{
              "width":10,
              "height":298}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/药品/u24_line.png"}},
{
          "id":"8a717738154f4cd685c681e0958db3fb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "opacity":"0.25",
            "location":{
              "x":455,
              "y":195},
            "size":{
              "width":222,
              "height":43},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF66FF00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22125141d0794e939722241ccb94e489",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "opacity":"0.25",
                "location":{
                  "x":455,
                  "y":195},
                "size":{
                  "width":222,
                  "height":43},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药品/u25.png"}},
{
          "id":"5a5062a87a6547a6b9d51a107c1e3123",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":470,
              "y":199},
            "size":{
              "width":141,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ec15006ced541488395e6ef25c8b394",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":470,
                  "y":199},
                "size":{
                  "width":141,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c42aecbf0474bae9940f2d543bc82c3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "opacity":"0.25",
            "location":{
              "x":455,
              "y":246},
            "size":{
              "width":222,
              "height":43},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF66FF00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81ac31ba1b2c4102a3f7dce3e6ef4afd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "opacity":"0.25",
                "location":{
                  "x":455,
                  "y":246},
                "size":{
                  "width":222,
                  "height":43},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药品/u25.png"}},
{
          "id":"3d0a9772bbed4d89ab8f0c8a21cf4f8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":470,
              "y":248},
            "size":{
              "width":190,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd6a1928713b494cae572a8551acc6df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":470,
                  "y":248},
                "size":{
                  "width":190,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9b2c65ce9b034325bf566db5952be560",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "opacity":"0.25",
            "location":{
              "x":455,
              "y":341},
            "size":{
              "width":222,
              "height":43},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF66FF00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"474dee83150a4dd1b620434c725894fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "opacity":"0.25",
                "location":{
                  "x":455,
                  "y":341},
                "size":{
                  "width":222,
                  "height":43},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药品/u25.png"}},
{
          "id":"048b0e481d584a98bdb3027d4d063efe",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":470,
              "y":345},
            "size":{
              "width":141,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c307cad7d7648d3b7ed74eedf1118be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":470,
                  "y":345},
                "size":{
                  "width":141,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e5a56d7de004dfa821460f880ccc543",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "opacity":"0.25",
            "location":{
              "x":455,
              "y":392},
            "size":{
              "width":222,
              "height":43},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF66FF00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71e6910abf91418ea16de6961eea0e17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "opacity":"0.25",
                "location":{
                  "x":455,
                  "y":392},
                "size":{
                  "width":222,
                  "height":43},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药品/u25.png"}},
{
          "id":"9c17fe3bf6a84d959401429becf16c24",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":470,
              "y":396},
            "size":{
              "width":190,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a18e4f89269941388883ce17ac04e271",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":470,
                  "y":396},
                "size":{
                  "width":190,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3766313a19d84e5f828bde96fc866573",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "opacity":"0.25",
            "location":{
              "x":455,
              "y":487},
            "size":{
              "width":222,
              "height":43},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF66FF00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eee7bc4ed9ef4fc4b7132263329739e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "opacity":"0.25",
                "location":{
                  "x":455,
                  "y":487},
                "size":{
                  "width":222,
                  "height":43},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药品/u25.png"}},
{
          "id":"ef9c4bd202cd498e969073b379028c50",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":470,
              "y":491},
            "size":{
              "width":141,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe68914d24334aa6938b66e24aac4336",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":470,
                  "y":491},
                "size":{
                  "width":141,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df740d305a6c460e94553a224da7bdef",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "opacity":"0.25",
            "location":{
              "x":455,
              "y":538},
            "size":{
              "width":222,
              "height":43},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF66FF00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb32ee4efbae4e73a855a90998ec9e34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "opacity":"0.25",
                "location":{
                  "x":455,
                  "y":538},
                "size":{
                  "width":222,
                  "height":43},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药品/u25.png"}},
{
          "id":"f173805154d54efe93a1b3fb42d89e57",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":470,
              "y":540},
            "size":{
              "width":198,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70208235a7e9460aac3470c7ba6fc358",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":470,
                  "y":540},
                "size":{
                  "width":198,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b859f8b471e04e789e778d15d431d667",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":86,
              "y":786},
            "size":{
              "width":262,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61ff363048714dbda75ffa366f0875e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":86,
                  "y":786},
                "size":{
                  "width":262,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药品/u49.png"}},
{
          "id":"5d726492821f43c6a55820682838b837",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":117,
              "y":794},
            "size":{
              "width":49,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"700d6eb4a4df4bb4a50cc8e1509b26e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":117,
                  "y":794},
                "size":{
                  "width":49,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u16.png"}},
{
          "id":"44358ee52ff64461a9a6600a32c8f213",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":161,
              "y":800},
            "size":{
              "width":170,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65f09164fec44e299a4a4f79e6bf3de4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":161,
                  "y":800},
                "size":{
                  "width":170,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"63b26e1a68084460bf56e609d9df26de",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":89,
              "y":941},
            "size":{
              "width":96,
              "height":96},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF66FF00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d91ef9cd6e644b2bcc61f05dbd872cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":89,
                  "y":941},
                "size":{
                  "width":96,
                  "height":96},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主角（暂停使用）/u14.png"}},
{
          "id":"17e1a74c418a4231bae07f74db60d52f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":210,
              "y":941},
            "size":{
              "width":96,
              "height":96},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF66FF00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18c6d1a19785449e8cec8368dcd678e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":210,
                  "y":941},
                "size":{
                  "width":96,
                  "height":96},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主角（暂停使用）/u14.png"}},
{
          "id":"50262e302d3a4ad9ba67ef2e2cd666dd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":331,
              "y":941},
            "size":{
              "width":96,
              "height":96},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF66FF00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4ceb229536946b6af8827fe09516bdc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":331,
                  "y":941},
                "size":{
                  "width":96,
                  "height":96},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主角（暂停使用）/u14.png"}},
{
          "id":"ad3e5d52c0d046a5886dc413655d3686",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":451,
              "y":941},
            "size":{
              "width":96,
              "height":96},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF66FF00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2a392e4cbee43d6811233f0b7228dcb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":451,
                  "y":941},
                "size":{
                  "width":96,
                  "height":96},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主角（暂停使用）/u14.png"}},
{
          "id":"aba67160a2444f50bb8e3f5465ff8a76",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":572,
              "y":941},
            "size":{
              "width":96,
              "height":96},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF66FF00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"002c43ac2123481687e0dd30ddcfdce5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":572,
                  "y":941},
                "size":{
                  "width":96,
                  "height":96},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主角（暂停使用）/u14.png"}},
{
          "id":"07d7ad72f14840f2b817a475e9b92c0c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":89,
              "y":1052},
            "size":{
              "width":96,
              "height":96},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF66FF00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e24137dff4c43ca9fd67e79fd76a43b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":89,
                  "y":1052},
                "size":{
                  "width":96,
                  "height":96},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主角（暂停使用）/u14.png"}},
{
          "id":"a71870d33d874582b26f3e2a66d4dce4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":210,
              "y":1052},
            "size":{
              "width":96,
              "height":96},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF66FF00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e941aea506649088276df22bd4d1387",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":210,
                  "y":1052},
                "size":{
                  "width":96,
                  "height":96},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主角（暂停使用）/u14.png"}},
{
          "id":"373b5ef3cd2641b99717f6747e159503",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":331,
              "y":1052},
            "size":{
              "width":96,
              "height":96},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF66FF00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2552abccb00d4c74a30f0658622da54c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":331,
                  "y":1052},
                "size":{
                  "width":96,
                  "height":96},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主角（暂停使用）/u14.png"}},
{
          "id":"29694f05d0054c1e8bd36d57efdb848c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":451,
              "y":1052},
            "size":{
              "width":96,
              "height":96},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF66FF00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d22527a483014b04845d3212ba940b62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":451,
                  "y":1052},
                "size":{
                  "width":96,
                  "height":96},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主角（暂停使用）/u14.png"}},
{
          "id":"2561f0b962264142854a9fb8637a6a7d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":572,
              "y":1052},
            "size":{
              "width":96,
              "height":96},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF66FF00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3474035ae1cc49c58e617351aa137bc7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":572,
                  "y":1052},
                "size":{
                  "width":96,
                  "height":96},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主角（暂停使用）/u14.png"}},
{
          "id":"0ec24a56557e477dbd18cddc6cab4339",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":89,
              "y":1163},
            "size":{
              "width":96,
              "height":96},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF66FF00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06bb5b5b511540829a19768d8e9df41a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":89,
                  "y":1163},
                "size":{
                  "width":96,
                  "height":96},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主角（暂停使用）/u14.png"}},
{
          "id":"b7eeeff0d52444b7a5fe096fa0da8f0d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":209,
              "y":1163},
            "size":{
              "width":96,
              "height":96},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF66FF00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c68bf341abd9420eac00ca0ee548db30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":209,
                  "y":1163},
                "size":{
                  "width":96,
                  "height":96},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主角（暂停使用）/u14.png"}},
{
          "id":"257ef6fd3f6447f79ef2b16d97a73458",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":331,
              "y":1163},
            "size":{
              "width":96,
              "height":96},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF66FF00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe90cc6aec3c441581e66829d10cdd51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":331,
                  "y":1163},
                "size":{
                  "width":96,
                  "height":96},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主角（暂停使用）/u14.png"}},
{
          "id":"72afddb79c904f798ae4d7a3cdc12584",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":451,
              "y":1163},
            "size":{
              "width":96,
              "height":96},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF66FF00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85ebc9c5ad73460b9599027ccc66a851",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":451,
                  "y":1163},
                "size":{
                  "width":96,
                  "height":96},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主角（暂停使用）/u14.png"}},
{
          "id":"e0f04a8b31574c559e70f8bfe30e328c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":571,
              "y":1163},
            "size":{
              "width":96,
              "height":96},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF66FF00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca053005c4484ccd91277d96e11bbd0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":571,
                  "y":1163},
                "size":{
                  "width":96,
                  "height":96},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主角（暂停使用）/u14.png"}},
{
          "id":"43f11e27f6ae48f79000350ef0ad72c0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":561,
              "y":930},
            "size":{
              "width":121,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01e47c40849145b6809f0ac10d492beb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":561,
                  "y":930},
                "size":{
                  "width":121,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u70.png"}},
{
          "id":"1159322d4b364bbab7d5970a72c5fb1a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":577,
              "y":947},
            "size":{
              "width":85,
              "height":85}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e1a1d081d5a45029b2dafd40936c7d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":577,
                  "y":947},
                "size":{
                  "width":85,
                  "height":85}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主角（暂停使用）/u124.png"}},
{
          "id":"0ca1f24dec9d4412a5a6f55efc80f30a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "opacity":"0.5",
            "location":{
              "x":106,
              "y":324},
            "size":{
              "width":128,
              "height":128}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8e5a96a38a147e9adb36dd363720262",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "opacity":"0.5",
                "location":{
                  "x":106,
                  "y":324},
                "size":{
                  "width":128,
                  "height":128}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主角（暂停使用）/u14.png"}},
{
          "id":"fefd2e69e9434855b5d6bf998280ad7b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "opacity":"0.5",
            "location":{
              "x":354,
              "y":484},
            "size":{
              "width":96,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35c0a0db3f2a45d5bcc6765e63dca866",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "opacity":"0.5",
                "location":{
                  "x":354,
                  "y":484},
                "size":{
                  "width":96,
                  "height":96}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主角（暂停使用）/u14.png"}},
{
          "id":"0d608ef17d7e41179b6f98522c053310",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "opacity":"0.5",
            "location":{
              "x":354,
              "y":340},
            "size":{
              "width":96,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3339c7b8a2f46c9a7dcf3445016161e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "opacity":"0.5",
                "location":{
                  "x":354,
                  "y":340},
                "size":{
                  "width":96,
                  "height":96}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主角（暂停使用）/u14.png"}},
{
          "id":"ad06aa0e457f435180cd55a37e0bb226",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "opacity":"0.5",
            "location":{
              "x":354,
              "y":193},
            "size":{
              "width":96,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b789b0e630d478c954553a404ed13d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "opacity":"0.5",
                "location":{
                  "x":354,
                  "y":193},
                "size":{
                  "width":96,
                  "height":96}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主角（暂停使用）/u14.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "aee9a39dff414dac92cb6f314479dfec":{
      "scriptId":"u0"},
    "0749b93143744cdfa3d378e277a17b62":{
      "scriptId":"u1"},
    "ce40f3fd2d8a4cc382f14c93d741e731":{
      "scriptId":"u2"},
    "540ad177143a4f689d11e7a27bf0b887":{
      "scriptId":"u3"},
    "ca05e1de32f04f1793cbf90001deed61":{
      "scriptId":"u4"},
    "e327bf63daf94ac9a579d5c42ab98519":{
      "scriptId":"u5"},
    "858abfe2560f4e82b95c29a6841800b6":{
      "scriptId":"u6"},
    "49b7b2a51c354cb48faabf10542eaefe":{
      "scriptId":"u7"},
    "2711342c5180499995a2184dc2b8d754":{
      "scriptId":"u8"},
    "4221d184b638443d9f072ad65f4ce7e5":{
      "scriptId":"u9"},
    "29affc9e389d42c9a2fac89da45c9625":{
      "scriptId":"u10"},
    "1ad79e2cccc44bc68aceb6ad591fb132":{
      "scriptId":"u11"},
    "849f63b671ba4ffba11eebf6845fd8bd":{
      "scriptId":"u12"},
    "ad73b02a9d5b4ee1962c67b2e3a82a72":{
      "scriptId":"u13"},
    "2e5dcdaa59764b658fd19c98c13b64a6":{
      "scriptId":"u14"},
    "e6fff608ad0947ebbdeb09b36af0f8b7":{
      "scriptId":"u15"},
    "3a96670bcffe4daab28ba1a4b6f0ed53":{
      "scriptId":"u16"},
    "fd7724ac30af4b7b91c0ae278fbfc21e":{
      "scriptId":"u17"},
    "8ea408e8cc4a44029af2efc3a22b8b04":{
      "scriptId":"u18"},
    "8bb89f96edd54a9bbab7e0bc58d4c7df":{
      "scriptId":"u19"},
    "24f9312cab4349e78f6ff2a23e6ffeeb":{
      "scriptId":"u20"},
    "67c1ec8679ee4deba30465f089f1c361":{
      "scriptId":"u21"},
    "81249983357943f8b7bee54b3c4b88ce":{
      "scriptId":"u22"},
    "c4ba490c8bab455b92ec957f7d45bf07":{
      "scriptId":"u23"},
    "ab350897e95b4fb3985b1006f7489c1b":{
      "scriptId":"u24"},
    "8a717738154f4cd685c681e0958db3fb":{
      "scriptId":"u25"},
    "22125141d0794e939722241ccb94e489":{
      "scriptId":"u26"},
    "5a5062a87a6547a6b9d51a107c1e3123":{
      "scriptId":"u27"},
    "2ec15006ced541488395e6ef25c8b394":{
      "scriptId":"u28"},
    "2c42aecbf0474bae9940f2d543bc82c3":{
      "scriptId":"u29"},
    "81ac31ba1b2c4102a3f7dce3e6ef4afd":{
      "scriptId":"u30"},
    "3d0a9772bbed4d89ab8f0c8a21cf4f8e":{
      "scriptId":"u31"},
    "bd6a1928713b494cae572a8551acc6df":{
      "scriptId":"u32"},
    "9b2c65ce9b034325bf566db5952be560":{
      "scriptId":"u33"},
    "474dee83150a4dd1b620434c725894fe":{
      "scriptId":"u34"},
    "048b0e481d584a98bdb3027d4d063efe":{
      "scriptId":"u35"},
    "6c307cad7d7648d3b7ed74eedf1118be":{
      "scriptId":"u36"},
    "0e5a56d7de004dfa821460f880ccc543":{
      "scriptId":"u37"},
    "71e6910abf91418ea16de6961eea0e17":{
      "scriptId":"u38"},
    "9c17fe3bf6a84d959401429becf16c24":{
      "scriptId":"u39"},
    "a18e4f89269941388883ce17ac04e271":{
      "scriptId":"u40"},
    "3766313a19d84e5f828bde96fc866573":{
      "scriptId":"u41"},
    "eee7bc4ed9ef4fc4b7132263329739e2":{
      "scriptId":"u42"},
    "ef9c4bd202cd498e969073b379028c50":{
      "scriptId":"u43"},
    "fe68914d24334aa6938b66e24aac4336":{
      "scriptId":"u44"},
    "df740d305a6c460e94553a224da7bdef":{
      "scriptId":"u45"},
    "fb32ee4efbae4e73a855a90998ec9e34":{
      "scriptId":"u46"},
    "f173805154d54efe93a1b3fb42d89e57":{
      "scriptId":"u47"},
    "70208235a7e9460aac3470c7ba6fc358":{
      "scriptId":"u48"},
    "b859f8b471e04e789e778d15d431d667":{
      "scriptId":"u49"},
    "61ff363048714dbda75ffa366f0875e2":{
      "scriptId":"u50"},
    "5d726492821f43c6a55820682838b837":{
      "scriptId":"u51"},
    "700d6eb4a4df4bb4a50cc8e1509b26e0":{
      "scriptId":"u52"},
    "44358ee52ff64461a9a6600a32c8f213":{
      "scriptId":"u53"},
    "65f09164fec44e299a4a4f79e6bf3de4":{
      "scriptId":"u54"},
    "63b26e1a68084460bf56e609d9df26de":{
      "scriptId":"u55"},
    "2d91ef9cd6e644b2bcc61f05dbd872cf":{
      "scriptId":"u56"},
    "17e1a74c418a4231bae07f74db60d52f":{
      "scriptId":"u57"},
    "18c6d1a19785449e8cec8368dcd678e5":{
      "scriptId":"u58"},
    "50262e302d3a4ad9ba67ef2e2cd666dd":{
      "scriptId":"u59"},
    "e4ceb229536946b6af8827fe09516bdc":{
      "scriptId":"u60"},
    "ad3e5d52c0d046a5886dc413655d3686":{
      "scriptId":"u61"},
    "e2a392e4cbee43d6811233f0b7228dcb":{
      "scriptId":"u62"},
    "aba67160a2444f50bb8e3f5465ff8a76":{
      "scriptId":"u63"},
    "002c43ac2123481687e0dd30ddcfdce5":{
      "scriptId":"u64"},
    "07d7ad72f14840f2b817a475e9b92c0c":{
      "scriptId":"u65"},
    "8e24137dff4c43ca9fd67e79fd76a43b":{
      "scriptId":"u66"},
    "a71870d33d874582b26f3e2a66d4dce4":{
      "scriptId":"u67"},
    "3e941aea506649088276df22bd4d1387":{
      "scriptId":"u68"},
    "373b5ef3cd2641b99717f6747e159503":{
      "scriptId":"u69"},
    "2552abccb00d4c74a30f0658622da54c":{
      "scriptId":"u70"},
    "29694f05d0054c1e8bd36d57efdb848c":{
      "scriptId":"u71"},
    "d22527a483014b04845d3212ba940b62":{
      "scriptId":"u72"},
    "2561f0b962264142854a9fb8637a6a7d":{
      "scriptId":"u73"},
    "3474035ae1cc49c58e617351aa137bc7":{
      "scriptId":"u74"},
    "0ec24a56557e477dbd18cddc6cab4339":{
      "scriptId":"u75"},
    "06bb5b5b511540829a19768d8e9df41a":{
      "scriptId":"u76"},
    "b7eeeff0d52444b7a5fe096fa0da8f0d":{
      "scriptId":"u77"},
    "c68bf341abd9420eac00ca0ee548db30":{
      "scriptId":"u78"},
    "257ef6fd3f6447f79ef2b16d97a73458":{
      "scriptId":"u79"},
    "fe90cc6aec3c441581e66829d10cdd51":{
      "scriptId":"u80"},
    "72afddb79c904f798ae4d7a3cdc12584":{
      "scriptId":"u81"},
    "85ebc9c5ad73460b9599027ccc66a851":{
      "scriptId":"u82"},
    "e0f04a8b31574c559e70f8bfe30e328c":{
      "scriptId":"u83"},
    "ca053005c4484ccd91277d96e11bbd0a":{
      "scriptId":"u84"},
    "43f11e27f6ae48f79000350ef0ad72c0":{
      "scriptId":"u85"},
    "01e47c40849145b6809f0ac10d492beb":{
      "scriptId":"u86"},
    "1159322d4b364bbab7d5970a72c5fb1a":{
      "scriptId":"u87"},
    "4e1a1d081d5a45029b2dafd40936c7d5":{
      "scriptId":"u88"},
    "0ca1f24dec9d4412a5a6f55efc80f30a":{
      "scriptId":"u89"},
    "c8e5a96a38a147e9adb36dd363720262":{
      "scriptId":"u90"},
    "fefd2e69e9434855b5d6bf998280ad7b":{
      "scriptId":"u91"},
    "35c0a0db3f2a45d5bcc6765e63dca866":{
      "scriptId":"u92"},
    "0d608ef17d7e41179b6f98522c053310":{
      "scriptId":"u93"},
    "a3339c7b8a2f46c9a7dcf3445016161e":{
      "scriptId":"u94"},
    "ad06aa0e457f435180cd55a37e0bb226":{
      "scriptId":"u95"},
    "8b789b0e630d478c954553a404ed13d8":{
      "scriptId":"u96"}}});