$axure.loadCurrentPage({
  "url":"付费.html",
  "generationDate":new Date(1491376840810.15),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"opentype"],
  "page":{
    "packageId":"2b31085b95a147ddbf936f569887c2cd",
    "type":"Axure:Page",
    "name":"付费",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"88fbb6d2fdf04096b7d40d43ae68363a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":20,
              "y":35},
            "size":{
              "width":734,
              "height":1295}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d04a28a2a7d46c79b1333592527b515",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":20,
                  "y":35},
                "size":{
                  "width":734,
                  "height":1295}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u0.png"}},
{
          "id":"0fe548e9af314c43bd6550bb84fa6f8a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":27,
              "y":43},
            "size":{
              "width":720,
              "height":1280}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62af0f0096af402dae6f5120729e0ca1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":27,
                  "y":43},
                "size":{
                  "width":720,
                  "height":1280}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主角（暂停使用）/u2.png"}},
{
          "id":"db994dd6567a4c1a94794c6e7009c6cd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":44,
              "y":105},
            "size":{
              "width":680,
              "height":1190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"053fcf16115a466492fbb534206f82d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":44,
                  "y":105},
                "size":{
                  "width":680,
                  "height":1190}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主角（暂停使用）/u4.png"}},
{
          "id":"d676446fe7614b6fbe4c947b81a11913",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":645,
              "y":47},
            "size":{
              "width":102,
              "height":98}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6df3d0d5725e4653816474e96af2c94f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":645,
                  "y":47},
                "size":{
                  "width":102,
                  "height":98}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主界面",
                      "target":{
                        "targetType":"page",
                        "url":"主界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/副本/u50.png"}},
{
          "id":"ddb24752f86a4d0090706885b717111d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":64,
              "y":1158},
            "size":{
              "width":152,
              "height":152}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80779ae5efdb4e0183631f74f5254827",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":64,
                  "y":1158},
                "size":{
                  "width":152,
                  "height":152}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/付费/u8.png"}},
{
          "id":"37078833ae6642cfa8dedcb2f3ba3d3f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":225,
              "y":1158},
            "size":{
              "width":152,
              "height":152}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bfeacf124144cdb95eeb5b789b2263f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":225,
                  "y":1158},
                "size":{
                  "width":152,
                  "height":152}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/付费/u8.png"}},
{
          "id":"aed6d37c007848079904fd6754a47e00",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":387,
              "y":1158},
            "size":{
              "width":152,
              "height":152}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2847d5251f1946918a79c2f7aeb9266d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":387,
                  "y":1158},
                "size":{
                  "width":152,
                  "height":152}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/付费/u8.png"}},
{
          "id":"480f321e5a7f4a1886ac6bb4547ad0e0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":548,
              "y":1158},
            "size":{
              "width":152,
              "height":152}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05f5bdc09a68407c9d4bef868aef50a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":548,
                  "y":1158},
                "size":{
                  "width":152,
                  "height":152}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/付费/u8.png"}},
{
          "id":"dc3052d6bc2c4d5792a45364c91805b3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":62,
              "y":1151},
            "size":{
              "width":156,
              "height":163}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da1ea52aa9b34122b57857633620ed88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":62,
                  "y":1151},
                "size":{
                  "width":156,
                  "height":163}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/付费/u16.png"}},
{
          "id":"3d60cb357cb34ef98dd2506f77fa2405",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":64,
              "y":1130},
            "size":{
              "width":636,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/付费/u18_line.png"}},
{
          "id":"6a39b79860584ebb9cafea5eae7cfe3d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":70,
              "y":185},
            "size":{
              "width":308,
              "height":345}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4b8304aa28d450b9d70b809a55a3c70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":70,
                  "y":185},
                "size":{
                  "width":308,
                  "height":345}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/付费/u19.png"}},
{
          "id":"3a77bd21bb5c4020b83cab6744202947",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":87,
              "y":457},
            "size":{
              "width":273,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"befa8d599d3942a5a19e2aaf7e30127a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":87,
                  "y":457},
                "size":{
                  "width":273,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/付费/u21.png"}},
{
          "id":"b37728169a254ba99a121f2ced61ed85",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":148,
              "y":240},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94150d5bc96245748842992a19c88a6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":148,
                  "y":240},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u16.png"}},
{
          "id":"df40ad1fb1464b1cbe4445a3c0aa3ece",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":122,
              "y":410},
            "size":{
              "width":202,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9ae7403446049d58f1600dd7a33e300",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":122,
                  "y":410},
                "size":{
                  "width":202,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d121e790bccd4027828fcaf9030f1d8f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":127,
              "y":462},
            "size":{
              "width":49,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb3a13b804b144619f24eac6f65e1566",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":127,
                  "y":462},
                "size":{
                  "width":49,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u22.png"}},
{
          "id":"b3c1dc09b06547bc94bb54ad0709303d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":176,
              "y":468},
            "size":{
              "width":144,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db294fc36c184fa8bf92474b862b0f97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":176,
                  "y":468},
                "size":{
                  "width":144,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b620d7d5ac994ef384c707f0ad38e0e8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":392,
              "y":185},
            "size":{
              "width":308,
              "height":345}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"487af283f0974a90b681f449e683ec5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":392,
                  "y":185},
                "size":{
                  "width":308,
                  "height":345}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/付费/u19.png"}},
{
          "id":"54de668fae15424bb1ae5e9d7cc4b872",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":409,
              "y":457},
            "size":{
              "width":273,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aaa0d22ff9dd406c8d57dad1c6d37d50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":409,
                  "y":457},
                "size":{
                  "width":273,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/付费/u21.png"}},
{
          "id":"23d6da08ab6845efa70ae0e51778b0f1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":470,
              "y":240},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"831ce7546da7489983ff98838def4355",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":470,
                  "y":240},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u16.png"}},
{
          "id":"b05ca25f23ac4292973af3fd37411f93",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":444,
              "y":410},
            "size":{
              "width":202,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"918e9886432a45d6a201a807c3325665",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":444,
                  "y":410},
                "size":{
                  "width":202,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f41feae4b4e44570a11444ca118504e1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":449,
              "y":462},
            "size":{
              "width":49,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acc64b48e70d43099440df674373862b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":449,
                  "y":462},
                "size":{
                  "width":49,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u22.png"}},
{
          "id":"695e973d29094e77a54f4fc3749c95c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":498,
              "y":468},
            "size":{
              "width":144,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3396aeb7327149af98d52df6112bf655",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":498,
                  "y":468},
                "size":{
                  "width":144,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d03ee304ede46a7a77dac44f29d950d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":70,
              "y":555},
            "size":{
              "width":308,
              "height":345}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2982a3518b864ca586a9b9aba19ae243",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":70,
                  "y":555},
                "size":{
                  "width":308,
                  "height":345}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/付费/u19.png"}},
{
          "id":"c7d7fe77b45a48b0ac86e3702af2d227",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":87,
              "y":827},
            "size":{
              "width":273,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61346ba438c24435b2eff10204afd9b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":87,
                  "y":827},
                "size":{
                  "width":273,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/付费/u21.png"}},
{
          "id":"8b7e69ff861a471dbdfb35305ee35162",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":148,
              "y":610},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d90c9e8bd2854b76925624dc817f0fc8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":148,
                  "y":610},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u16.png"}},
{
          "id":"f0dd1b13df414f33a2c5c8bf0afa637b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":122,
              "y":780},
            "size":{
              "width":202,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"083e94afec8c494d931eb2c9809d7a61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":122,
                  "y":780},
                "size":{
                  "width":202,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"498f3c5cea004e7fa6502ea19f380454",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":127,
              "y":832},
            "size":{
              "width":49,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b93e1b73e48e441a92751511c51a371b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":127,
                  "y":832},
                "size":{
                  "width":49,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u22.png"}},
{
          "id":"49070dcfd1484094bf03682b3921fe63",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":176,
              "y":838},
            "size":{
              "width":144,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72f722e7475e40e5afa2395ad0fb4cab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":176,
                  "y":838},
                "size":{
                  "width":144,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"10e728947ac045f5b789a7c3940e1cd8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":392,
              "y":555},
            "size":{
              "width":308,
              "height":345}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2856452f8de4f2e9899fa2fc49d9ef5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":392,
                  "y":555},
                "size":{
                  "width":308,
                  "height":345}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/付费/u19.png"}},
{
          "id":"d7b8d483836a4cd88f72f8fb8f1608ed",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":409,
              "y":827},
            "size":{
              "width":273,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0660b0b18a6e4999975fe465f020e63a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":409,
                  "y":827},
                "size":{
                  "width":273,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/付费/u21.png"}},
{
          "id":"652babeacc3b4800a2ad46d541b8c3e6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":470,
              "y":610},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73e8830419604596ab1b625daf37862a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":470,
                  "y":610},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u16.png"}},
{
          "id":"1efcd6f2bac4421cb0897579ba808b3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":444,
              "y":780},
            "size":{
              "width":202,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fe1abe4cc884769b9a630ec2f7884e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":444,
                  "y":780},
                "size":{
                  "width":202,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3ccf49f2a57a466dabd6339254103276",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":449,
              "y":832},
            "size":{
              "width":49,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a43f103bb4c4417984a987dd1be1637b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":449,
                  "y":832},
                "size":{
                  "width":49,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u22.png"}},
{
          "id":"c2493bd3773c49f484cb8607aee20f53",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":498,
              "y":838},
            "size":{
              "width":144,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01b99e2a68b74c4383bea8fcb384ca82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":498,
                  "y":838},
                "size":{
                  "width":144,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"71946e3e8cbe4acea7d11193ab9cd0d8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":73,
              "y":203},
            "size":{
              "width":204,
              "height":100},
            "rotation":"321",
            "textRotation":"321"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"117b7a7e12004246b79094be0925984a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":73,
                  "y":203},
                "size":{
                  "width":204,
                  "height":100},
                "rotation":"321",
                "textRotation":"321"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗/u78.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "88fbb6d2fdf04096b7d40d43ae68363a":{
      "scriptId":"u0"},
    "5d04a28a2a7d46c79b1333592527b515":{
      "scriptId":"u1"},
    "0fe548e9af314c43bd6550bb84fa6f8a":{
      "scriptId":"u2"},
    "62af0f0096af402dae6f5120729e0ca1":{
      "scriptId":"u3"},
    "db994dd6567a4c1a94794c6e7009c6cd":{
      "scriptId":"u4"},
    "053fcf16115a466492fbb534206f82d3":{
      "scriptId":"u5"},
    "d676446fe7614b6fbe4c947b81a11913":{
      "scriptId":"u6"},
    "6df3d0d5725e4653816474e96af2c94f":{
      "scriptId":"u7"},
    "ddb24752f86a4d0090706885b717111d":{
      "scriptId":"u8"},
    "80779ae5efdb4e0183631f74f5254827":{
      "scriptId":"u9"},
    "37078833ae6642cfa8dedcb2f3ba3d3f":{
      "scriptId":"u10"},
    "6bfeacf124144cdb95eeb5b789b2263f":{
      "scriptId":"u11"},
    "aed6d37c007848079904fd6754a47e00":{
      "scriptId":"u12"},
    "2847d5251f1946918a79c2f7aeb9266d":{
      "scriptId":"u13"},
    "480f321e5a7f4a1886ac6bb4547ad0e0":{
      "scriptId":"u14"},
    "05f5bdc09a68407c9d4bef868aef50a3":{
      "scriptId":"u15"},
    "dc3052d6bc2c4d5792a45364c91805b3":{
      "scriptId":"u16"},
    "da1ea52aa9b34122b57857633620ed88":{
      "scriptId":"u17"},
    "3d60cb357cb34ef98dd2506f77fa2405":{
      "scriptId":"u18"},
    "6a39b79860584ebb9cafea5eae7cfe3d":{
      "scriptId":"u19"},
    "a4b8304aa28d450b9d70b809a55a3c70":{
      "scriptId":"u20"},
    "3a77bd21bb5c4020b83cab6744202947":{
      "scriptId":"u21"},
    "befa8d599d3942a5a19e2aaf7e30127a":{
      "scriptId":"u22"},
    "b37728169a254ba99a121f2ced61ed85":{
      "scriptId":"u23"},
    "94150d5bc96245748842992a19c88a6a":{
      "scriptId":"u24"},
    "df40ad1fb1464b1cbe4445a3c0aa3ece":{
      "scriptId":"u25"},
    "e9ae7403446049d58f1600dd7a33e300":{
      "scriptId":"u26"},
    "d121e790bccd4027828fcaf9030f1d8f":{
      "scriptId":"u27"},
    "fb3a13b804b144619f24eac6f65e1566":{
      "scriptId":"u28"},
    "b3c1dc09b06547bc94bb54ad0709303d":{
      "scriptId":"u29"},
    "db294fc36c184fa8bf92474b862b0f97":{
      "scriptId":"u30"},
    "b620d7d5ac994ef384c707f0ad38e0e8":{
      "scriptId":"u31"},
    "487af283f0974a90b681f449e683ec5d":{
      "scriptId":"u32"},
    "54de668fae15424bb1ae5e9d7cc4b872":{
      "scriptId":"u33"},
    "aaa0d22ff9dd406c8d57dad1c6d37d50":{
      "scriptId":"u34"},
    "23d6da08ab6845efa70ae0e51778b0f1":{
      "scriptId":"u35"},
    "831ce7546da7489983ff98838def4355":{
      "scriptId":"u36"},
    "b05ca25f23ac4292973af3fd37411f93":{
      "scriptId":"u37"},
    "918e9886432a45d6a201a807c3325665":{
      "scriptId":"u38"},
    "f41feae4b4e44570a11444ca118504e1":{
      "scriptId":"u39"},
    "acc64b48e70d43099440df674373862b":{
      "scriptId":"u40"},
    "695e973d29094e77a54f4fc3749c95c3":{
      "scriptId":"u41"},
    "3396aeb7327149af98d52df6112bf655":{
      "scriptId":"u42"},
    "4d03ee304ede46a7a77dac44f29d950d":{
      "scriptId":"u43"},
    "2982a3518b864ca586a9b9aba19ae243":{
      "scriptId":"u44"},
    "c7d7fe77b45a48b0ac86e3702af2d227":{
      "scriptId":"u45"},
    "61346ba438c24435b2eff10204afd9b0":{
      "scriptId":"u46"},
    "8b7e69ff861a471dbdfb35305ee35162":{
      "scriptId":"u47"},
    "d90c9e8bd2854b76925624dc817f0fc8":{
      "scriptId":"u48"},
    "f0dd1b13df414f33a2c5c8bf0afa637b":{
      "scriptId":"u49"},
    "083e94afec8c494d931eb2c9809d7a61":{
      "scriptId":"u50"},
    "498f3c5cea004e7fa6502ea19f380454":{
      "scriptId":"u51"},
    "b93e1b73e48e441a92751511c51a371b":{
      "scriptId":"u52"},
    "49070dcfd1484094bf03682b3921fe63":{
      "scriptId":"u53"},
    "72f722e7475e40e5afa2395ad0fb4cab":{
      "scriptId":"u54"},
    "10e728947ac045f5b789a7c3940e1cd8":{
      "scriptId":"u55"},
    "a2856452f8de4f2e9899fa2fc49d9ef5":{
      "scriptId":"u56"},
    "d7b8d483836a4cd88f72f8fb8f1608ed":{
      "scriptId":"u57"},
    "0660b0b18a6e4999975fe465f020e63a":{
      "scriptId":"u58"},
    "652babeacc3b4800a2ad46d541b8c3e6":{
      "scriptId":"u59"},
    "73e8830419604596ab1b625daf37862a":{
      "scriptId":"u60"},
    "1efcd6f2bac4421cb0897579ba808b3b":{
      "scriptId":"u61"},
    "7fe1abe4cc884769b9a630ec2f7884e9":{
      "scriptId":"u62"},
    "3ccf49f2a57a466dabd6339254103276":{
      "scriptId":"u63"},
    "a43f103bb4c4417984a987dd1be1637b":{
      "scriptId":"u64"},
    "c2493bd3773c49f484cb8607aee20f53":{
      "scriptId":"u65"},
    "01b99e2a68b74c4383bea8fcb384ca82":{
      "scriptId":"u66"},
    "71946e3e8cbe4acea7d11193ab9cd0d8":{
      "scriptId":"u67"},
    "117b7a7e12004246b79094be0925984a":{
      "scriptId":"u68"}}});