$axure.loadCurrentPage({
  "url":"设置.html",
  "generationDate":new Date(1491376839498.07),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"opentype"],
  "page":{
    "packageId":"c2a93bb5348c4125ab4b74da3e4c88bc",
    "type":"Axure:Page",
    "name":"设置",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f28ef10dc0f1418ab0d76b2c7cad6bb1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":30,
              "y":30},
            "size":{
              "width":734,
              "height":1295}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e01488f12016430da25465dd6d817b10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":30,
                  "y":30},
                "size":{
                  "width":734,
                  "height":1295}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u0.png"}},
{
          "id":"a78e85af9ad648f9b31b95ae6d40d2fc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":37,
              "y":38},
            "size":{
              "width":720,
              "height":1280}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1aa2725f35241da9afbc8c067c3cc27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":37,
                  "y":38},
                "size":{
                  "width":720,
                  "height":1280}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主角（暂停使用）/u2.png"}},
{
          "id":"3f26201fb46c48c8a588f41171cbc047",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":54,
              "y":95},
            "size":{
              "width":680,
              "height":1200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb17c7e10b294ef4b7c3705d153b94c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":54,
                  "y":95},
                "size":{
                  "width":680,
                  "height":1200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/统计/u4.png"}},
{
          "id":"7631dc6c1ff54c51ba9b70faa702a986",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":655,
              "y":47},
            "size":{
              "width":102,
              "height":98}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f1327b9f6434af6ae3739f4baf5304f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":655,
                  "y":47},
                "size":{
                  "width":102,
                  "height":98}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主界面",
                      "target":{
                        "targetType":"page",
                        "url":"主界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/副本/u50.png"}},
{
          "id":"4b98695c93f6463cb559f83f8b5547fc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":182,
              "y":225},
            "size":{
              "width":112,
              "height":112}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4b20178ffb140e9b31666773f24d0a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":182,
                  "y":225},
                "size":{
                  "width":112,
                  "height":112}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置/u8.png"}},
{
          "id":"c45c5079fb984247bbd38138885a63d0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":182,
              "y":439},
            "size":{
              "width":118,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60682dcd31b8446f976d59372bd4773a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":182,
                  "y":439},
                "size":{
                  "width":118,
                  "height":96}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置/u10.png"}},
{
          "id":"00d9f0280d8244b7b51bae90400e2ac6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":445,
              "y":225},
            "size":{
              "width":159,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"619a60439dfc4e679a1e36addbb9718e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":445,
                  "y":225},
                "size":{
                  "width":159,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置/u12.png"}},
{
          "id":"aaab8dbe91554bd2b363d97339940672",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":445,
              "y":427},
            "size":{
              "width":159,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"392e93b90e044b17900ebfc66f887a07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":445,
                  "y":427},
                "size":{
                  "width":159,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置/u12.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "f28ef10dc0f1418ab0d76b2c7cad6bb1":{
      "scriptId":"u0"},
    "e01488f12016430da25465dd6d817b10":{
      "scriptId":"u1"},
    "a78e85af9ad648f9b31b95ae6d40d2fc":{
      "scriptId":"u2"},
    "e1aa2725f35241da9afbc8c067c3cc27":{
      "scriptId":"u3"},
    "3f26201fb46c48c8a588f41171cbc047":{
      "scriptId":"u4"},
    "fb17c7e10b294ef4b7c3705d153b94c4":{
      "scriptId":"u5"},
    "7631dc6c1ff54c51ba9b70faa702a986":{
      "scriptId":"u6"},
    "0f1327b9f6434af6ae3739f4baf5304f":{
      "scriptId":"u7"},
    "4b98695c93f6463cb559f83f8b5547fc":{
      "scriptId":"u8"},
    "c4b20178ffb140e9b31666773f24d0a6":{
      "scriptId":"u9"},
    "c45c5079fb984247bbd38138885a63d0":{
      "scriptId":"u10"},
    "60682dcd31b8446f976d59372bd4773a":{
      "scriptId":"u11"},
    "00d9f0280d8244b7b51bae90400e2ac6":{
      "scriptId":"u12"},
    "619a60439dfc4e679a1e36addbb9718e":{
      "scriptId":"u13"},
    "aaab8dbe91554bd2b363d97339940672":{
      "scriptId":"u14"},
    "392e93b90e044b17900ebfc66f887a07":{
      "scriptId":"u15"}}});