$axure.loadCurrentPage({
  "url":"飞船.html",
  "generationDate":new Date(1491376844087.33),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"opentype"],
  "page":{
    "packageId":"00b01be0b81a4b27930f78e5cd304228",
    "type":"Axure:Page",
    "name":"飞船",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d476c9cd7cb74d1bbaa44ea524ce45be",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":20,
              "y":35},
            "size":{
              "width":734,
              "height":1295}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"691cdfc1b5e340eab9a6f1a1f02f2798",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":20,
                  "y":35},
                "size":{
                  "width":734,
                  "height":1295}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u0.png"}},
{
          "id":"d3eb9f29f6c24c1e9b1430bff20f0fa5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":27,
              "y":43},
            "size":{
              "width":720,
              "height":1280}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf6636e0ed0e480da7b62052b263b4df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":27,
                  "y":43},
                "size":{
                  "width":720,
                  "height":1280}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主角（暂停使用）/u2.png"}},
{
          "id":"00bc3c558e814917a614c0889b9ffbf6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":44,
              "y":105},
            "size":{
              "width":680,
              "height":1190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"935f887ec13f4dcab44a40141d0097ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":44,
                  "y":105},
                "size":{
                  "width":680,
                  "height":1190}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主角（暂停使用）/u4.png"}},
{
          "id":"25b97b0cc68446eab61b204ebdbe6b7a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":645,
              "y":47},
            "size":{
              "width":102,
              "height":98}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"609ed00ac86e441c8ab5d48ea40e2f7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":645,
                  "y":47},
                "size":{
                  "width":102,
                  "height":98}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主界面",
                      "target":{
                        "targetType":"page",
                        "url":"主界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/副本/u50.png"}},
{
          "id":"66748ae8e45e4d7bae5188a62d60da01",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":164,
              "y":482},
            "size":{
              "width":448,
              "height":380}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2435466568c041119a380e04360e9209",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":164,
                  "y":482},
                "size":{
                  "width":448,
                  "height":380}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/飞船/u8.png"}},
{
          "id":"746a20de6e2a4dc7afd86573bab1a9ac",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":404,
              "y":361},
            "size":{
              "width":208,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d7c24f577f14ad18f158eadb7ac791a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":404,
                  "y":361},
                "size":{
                  "width":208,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 信息,<br>待解锁,<br>隐藏 解锁中,<br>修复",
                      "objectsToFades":[{
                          "objectPath":["995b648e560743318b0bc35445a21b9b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["469562963ed34f93b1a7f8de43272d0d"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["7311be73b7594f03b8052687097dcee2"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["421fe8ad6a654ff080103a6bee249e85"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/飞船/u10.png"}},
{
          "id":"91a3351ca7d141c9a70623bcc886e560",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":66,
              "y":481},
            "size":{
              "width":208,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e73295ad94d2401381d520cf65208427",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":66,
                  "y":481},
                "size":{
                  "width":208,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 信息,<br>待解锁,<br>隐藏 解锁中,<br>修复",
                      "objectsToFades":[{
                          "objectPath":["995b648e560743318b0bc35445a21b9b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["469562963ed34f93b1a7f8de43272d0d"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["7311be73b7594f03b8052687097dcee2"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["421fe8ad6a654ff080103a6bee249e85"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/飞船/u10.png"}},
{
          "id":"acb970ee20784209bab9db94dfe70938",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":494,
              "y":536},
            "size":{
              "width":208,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"deb000cdcc974023b44ce3d6a3386871",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":494,
                  "y":536},
                "size":{
                  "width":208,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 信息,<br>待解锁,<br>隐藏 解锁中,<br>修复",
                      "objectsToFades":[{
                          "objectPath":["995b648e560743318b0bc35445a21b9b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["469562963ed34f93b1a7f8de43272d0d"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["7311be73b7594f03b8052687097dcee2"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["421fe8ad6a654ff080103a6bee249e85"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/飞船/u10.png"}},
{
          "id":"04f93bc9a676484f8766eb5d8555fac6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":494,
              "y":870},
            "size":{
              "width":208,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a7a53eec2c64bf4b8941fe4b987cb7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":494,
                  "y":870},
                "size":{
                  "width":208,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 信息,<br>待解锁,<br>隐藏 解锁中,<br>修复",
                      "objectsToFades":[{
                          "objectPath":["995b648e560743318b0bc35445a21b9b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["469562963ed34f93b1a7f8de43272d0d"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["7311be73b7594f03b8052687097dcee2"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["421fe8ad6a654ff080103a6bee249e85"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/飞船/u10.png"}},
{
          "id":"f2a607466597463990d4419597a72064",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":399,
              "y":824},
            "size":{
              "width":124,
              "height":6},
            "rotation":"45",
            "textRotation":"45"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5673377a5334bcbbe4d36c5931b8460",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":399,
                  "y":824},
                "size":{
                  "width":124,
                  "height":6},
                "rotation":"45",
                "textRotation":"45"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/飞船/u18.png"}},
{
          "id":"ca1d8b686d1d4d47a7b1f68c1a39316d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":372,
              "y":616},
            "size":{
              "width":193,
              "height":6},
            "rotation":"345",
            "textRotation":"345"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a8d3d55cea749bf9fb7b90991f48e5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":372,
                  "y":616},
                "size":{
                  "width":193,
                  "height":6},
                "rotation":"345",
                "textRotation":"345"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/飞船/u20.png"}},
{
          "id":"6bbdabc8de694a5080109e114dff0361",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":137,
              "y":598},
            "size":{
              "width":193,
              "height":6},
            "rotation":"45",
            "textRotation":"45"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8960deb34aec45fdbd19ba8648723fde",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":137,
                  "y":598},
                "size":{
                  "width":193,
                  "height":6},
                "rotation":"45",
                "textRotation":"45"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/飞船/u20.png"}},
{
          "id":"4e1decc8d1eb41778ccdbedb65dbf0a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":359,
              "y":463},
            "size":{
              "width":121,
              "height":6},
            "rotation":"315",
            "textRotation":"315"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2525746bdaf84be3974b4b92ae3c8d3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":359,
                  "y":463},
                "size":{
                  "width":121,
                  "height":6},
                "rotation":"315",
                "textRotation":"315"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/飞船/u24.png"}},
{
          "id":"a6bc64f957414258b824e79be2ad0087",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":66,
              "y":813},
            "size":{
              "width":208,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1958e028a46a452bbbd76b95ce401c08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":66,
                  "y":813},
                "size":{
                  "width":208,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 信息,<br>待解锁,<br>隐藏 解锁中,<br>修复",
                      "objectsToFades":[{
                          "objectPath":["995b648e560743318b0bc35445a21b9b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["469562963ed34f93b1a7f8de43272d0d"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["7311be73b7594f03b8052687097dcee2"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["421fe8ad6a654ff080103a6bee249e85"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/飞船/u10.png"}},
{
          "id":"8ee2c66318c24386a8fa68a58b70fff2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":241,
              "y":761},
            "size":{
              "width":161,
              "height":6},
            "rotation":"135",
            "textRotation":"135"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"854052b4d76a4495a8984228429ddb95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":241,
                  "y":761},
                "size":{
                  "width":161,
                  "height":6},
                "rotation":"135",
                "textRotation":"135"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/飞船/u28.png"}},
{
          "id":"995b648e560743318b0bc35445a21b9b",
          "label":"信息",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":60,
              "y":647},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"84de40d5595a4509af42bbb652c41ecf",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"b11d5c58319c4f61af36334b927a8fbd",
                  "label":"",
                  "parentDynamicPanel":"995b648e560743318b0bc35445a21b9b",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "location":{
                      "x":0,
                      "y":38},
                    "size":{
                      "width":635,
                      "height":590}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3d16528b0efc487e87921d9e4db0c546",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"995b648e560743318b0bc35445a21b9b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "location":{
                          "x":0,
                          "y":38},
                        "size":{
                          "width":635,
                          "height":590}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/飞船/u31.png"}},
{
                  "id":"57d8d85664f34775a03a02802a734fd3",
                  "label":"",
                  "parentDynamicPanel":"995b648e560743318b0bc35445a21b9b",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "location":{
                      "x":548,
                      "y":3},
                    "size":{
                      "width":102,
                      "height":98}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5a3c4552fb7749b1a948a7c61d14e0f8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"995b648e560743318b0bc35445a21b9b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "location":{
                          "x":548,
                          "y":3},
                        "size":{
                          "width":102,
                          "height":98}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 信息",
                              "objectsToFades":[{
                                  "objectPath":["995b648e560743318b0bc35445a21b9b"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/副本/u50.png"}},
{
                  "id":"1924225e95e6462d9c200c31be09fe5c",
                  "label":"",
                  "parentDynamicPanel":"995b648e560743318b0bc35445a21b9b",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":144,
                      "y":3},
                    "size":{
                      "width":309,
                      "height":75}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"63c96283594e4f08b702a817533506c5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"995b648e560743318b0bc35445a21b9b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":144,
                          "y":3},
                        "size":{
                          "width":309,
                          "height":75}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/副本/u64.png"}},
{
                  "id":"db99165ac3aa40fdbf227aea3895ae2f",
                  "label":"",
                  "parentDynamicPanel":"995b648e560743318b0bc35445a21b9b",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":229,
                      "y":10},
                    "size":{
                      "width":137,
                      "height":55}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b9b5df246f5d4a1380c7b840d70dd37f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"995b648e560743318b0bc35445a21b9b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":229,
                          "y":10},
                        "size":{
                          "width":137,
                          "height":55}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"68b2f091d0f9426f99691fbbc2c390a9",
                  "label":"",
                  "parentDynamicPanel":"995b648e560743318b0bc35445a21b9b",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":7,
                      "y":497},
                    "size":{
                      "width":620,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/主角（暂停使用）/u114_line.png"}},
{
                  "id":"7b32ebda2c274a818eb812d6bd1c3843",
                  "label":"",
                  "parentDynamicPanel":"995b648e560743318b0bc35445a21b9b",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "opacity":"0.25",
                    "location":{
                      "x":20,
                      "y":430},
                    "size":{
                      "width":600,
                      "height":58},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF66FF00}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"df5180a2f5614effb9da7dd7162c619b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"995b648e560743318b0bc35445a21b9b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "opacity":"0.25",
                        "location":{
                          "x":20,
                          "y":430},
                        "size":{
                          "width":600,
                          "height":58},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF66FF00}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/飞船/u40.png"}},
{
                  "id":"4eca187903d8462f880d95e5ab4eda51",
                  "label":"",
                  "parentDynamicPanel":"995b648e560743318b0bc35445a21b9b",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "location":{
                      "x":40,
                      "y":439},
                    "size":{
                      "width":560,
                      "height":42}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cb32f5e95b4f41b78d9eb3d797137240",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"995b648e560743318b0bc35445a21b9b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "location":{
                          "x":40,
                          "y":439},
                        "size":{
                          "width":560,
                          "height":42}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/飞船/u42.png"}},
{
                  "id":"4ca28912140f49c6925e1da43b55698e",
                  "label":"",
                  "parentDynamicPanel":"995b648e560743318b0bc35445a21b9b",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "location":{
                      "x":48,
                      "y":446},
                    "size":{
                      "width":292,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eb12d0516faf4e55a6b58c703127a2ce",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"995b648e560743318b0bc35445a21b9b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "location":{
                          "x":48,
                          "y":446},
                        "size":{
                          "width":292,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/飞船/u44.png"}},
{
                  "id":"22bd5f1d2f5440f6b96e6586d263d7c3",
                  "label":"",
                  "parentDynamicPanel":"995b648e560743318b0bc35445a21b9b",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "opacity":"0.25",
                    "location":{
                      "x":17,
                      "y":130},
                    "size":{
                      "width":600,
                      "height":290},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF66FF00}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8e3cbdb03aca4e17b19fedbf79f4e800",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"995b648e560743318b0bc35445a21b9b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "opacity":"0.25",
                        "location":{
                          "x":17,
                          "y":130},
                        "size":{
                          "width":600,
                          "height":290},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF66FF00}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/飞船/u46.png"}},
{
                  "id":"469562963ed34f93b1a7f8de43272d0d",
                  "label":"待解锁",
                  "parentDynamicPanel":"995b648e560743318b0bc35445a21b9b",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":67.5,
                      "y":207},
                    "size":{
                      "width":10,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"c1c5fa58dd0c4c69800a56fab916d069",
                      "label":"状态1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"af73f95cbfe640c79d011dabf6b9685a",
                          "label":"",
                          "parentDynamicPanel":"469562963ed34f93b1a7f8de43272d0d",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "fontSize":"28px",
                            "location":{
                              "x":141,
                              "y":322},
                            "size":{
                              "width":187,
                              "height":71}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"fb7f7837a69d41b8b51a73a472b57fde",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"469562963ed34f93b1a7f8de43272d0d",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"28px",
                                "location":{
                                  "x":141,
                                  "y":322},
                                "size":{
                                  "width":187,
                                  "height":71}},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"fadeWidget",
                                      "description":"显示 解锁中,<br>隐藏 待解锁",
                                      "objectsToFades":[{
                                          "objectPath":["469562963ed34f93b1a7f8de43272d0d"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "showType":"none"}}},
{
                                          "objectPath":["7311be73b7594f03b8052687097dcee2"],
                                          "fadeInfo":{
                                            "fadeType":"show",
                                            "options":{
                                              "showType":"none"}}}]}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"images/主界面/u6.png"}},
{
                          "id":"acde07733d314475bd1ee81bde7c58d1",
                          "label":"",
                          "parentDynamicPanel":"469562963ed34f93b1a7f8de43272d0d",
                          "type":"buttonShape",
                          "styleType":"h1",
                          "visible":true,
                          "style":{
                            "fontSize":"28px",
                            "horizontalAlignment":"center",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "size":{
                              "width":505,
                              "height":312}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"8ef2c976aad34bb7b2cd11a1145b78ed",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"469562963ed34f93b1a7f8de43272d0d",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"28px",
                                "horizontalAlignment":"center",
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFFFF,
                                  "opacity":1},
                                "size":{
                                  "width":505,
                                  "height":312}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"900499f9d6d14da0a8a5388c5d7f5de6",
                          "label":"",
                          "parentDynamicPanel":"469562963ed34f93b1a7f8de43272d0d",
                          "type":"horizontalLine",
                          "styleType":"horizontalLine",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":-28,
                              "y":66},
                            "size":{
                              "width":560,
                              "height":10}},
                          "adaptiveStyles":{
},
                          "images":{
                            "start~":"resources/images/transparent.gif",
                            "end~":"resources/images/transparent.gif",
                            "line~":"images/飞船/u53_line.png"}}]}]},
{
                  "id":"7311be73b7594f03b8052687097dcee2",
                  "label":"解锁中",
                  "parentDynamicPanel":"995b648e560743318b0bc35445a21b9b",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":31,
                      "y":136},
                    "size":{
                      "width":10,
                      "height":10},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"807105a8c9ad4433bd2f5b54af4cc666",
                      "label":"状态1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"96ee00d2c4494fe2af32acd43f3f91fb",
                          "label":"",
                          "parentDynamicPanel":"7311be73b7594f03b8052687097dcee2",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "fontSize":"28px",
                            "location":{
                              "x":177,
                              "y":393},
                            "size":{
                              "width":187,
                              "height":71}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"6af37a4c4d3a4a2f9453b491c577e171",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"7311be73b7594f03b8052687097dcee2",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"28px",
                                "location":{
                                  "x":177,
                                  "y":393},
                                "size":{
                                  "width":187,
                                  "height":71}},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"fadeWidget",
                                      "description":"显示 修复,<br>隐藏 信息",
                                      "objectsToFades":[{
                                          "objectPath":["995b648e560743318b0bc35445a21b9b"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "showType":"none"}}},
{
                                          "objectPath":["421fe8ad6a654ff080103a6bee249e85"],
                                          "fadeInfo":{
                                            "fadeType":"show",
                                            "options":{
                                              "showType":"none"}}}]}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"images/主界面/u6.png"}},
{
                          "id":"81d38a038b06497c91566ca836f5873c",
                          "label":"",
                          "parentDynamicPanel":"7311be73b7594f03b8052687097dcee2",
                          "type":"buttonShape",
                          "styleType":"h1",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "size":{
                              "width":544,
                              "height":279}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"e5d02933b0724b09bbd3c5130e8c1134",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"7311be73b7594f03b8052687097dcee2",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"16px",
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFFFF,
                                  "opacity":1},
                                "size":{
                                  "width":544,
                                  "height":279}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"c91ead941ab6493594015ceaa0b3cc17",
                          "label":"",
                          "parentDynamicPanel":"7311be73b7594f03b8052687097dcee2",
                          "type":"horizontalLine",
                          "styleType":"horizontalLine",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":0,
                              "y":24},
                            "size":{
                              "width":569,
                              "height":10}},
                          "adaptiveStyles":{
},
                          "images":{
                            "start~":"resources/images/transparent.gif",
                            "end~":"resources/images/transparent.gif",
                            "line~":"images/飞船/u59_line.png"}}]}]}]}]},
{
          "id":"421fe8ad6a654ff080103a6bee249e85",
          "label":"修复",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":60,
              "y":647},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"06d6565793b949b08ef286cd3c50b462",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"1d5d139f133148518d59cab5bfac4f29",
                  "label":"",
                  "parentDynamicPanel":"421fe8ad6a654ff080103a6bee249e85",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "location":{
                      "x":0,
                      "y":38},
                    "size":{
                      "width":635,
                      "height":590}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4c61a572d9cc4362b45bc3f908ab895d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"421fe8ad6a654ff080103a6bee249e85",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "location":{
                          "x":0,
                          "y":38},
                        "size":{
                          "width":635,
                          "height":590}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/飞船/u31.png"}},
{
                  "id":"8d798a124cd6403aae062a4ee9a0e602",
                  "label":"",
                  "parentDynamicPanel":"421fe8ad6a654ff080103a6bee249e85",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "location":{
                      "x":548,
                      "y":3},
                    "size":{
                      "width":102,
                      "height":98}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"343e807d4ad341988218d07722bc5a07",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"421fe8ad6a654ff080103a6bee249e85",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "location":{
                          "x":548,
                          "y":3},
                        "size":{
                          "width":102,
                          "height":98}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 修复",
                              "objectsToFades":[{
                                  "objectPath":["421fe8ad6a654ff080103a6bee249e85"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/副本/u50.png"}},
{
                  "id":"51ff473ba75e499ab122485659662efc",
                  "label":"",
                  "parentDynamicPanel":"421fe8ad6a654ff080103a6bee249e85",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":144,
                      "y":3},
                    "size":{
                      "width":309,
                      "height":75}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"541b5dc4429a42628939a15021596ccf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"421fe8ad6a654ff080103a6bee249e85",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":144,
                          "y":3},
                        "size":{
                          "width":309,
                          "height":75}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/副本/u64.png"}},
{
                  "id":"fe4b31be59634f128eedf4e8b358e7f0",
                  "label":"",
                  "parentDynamicPanel":"421fe8ad6a654ff080103a6bee249e85",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":229,
                      "y":10},
                    "size":{
                      "width":137,
                      "height":55}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ca274b280c5d4838ae4e039d5cffb974",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"421fe8ad6a654ff080103a6bee249e85",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":229,
                          "y":10},
                        "size":{
                          "width":137,
                          "height":55}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a122b365e5784abb97f496545a3d25c9",
                  "label":"",
                  "parentDynamicPanel":"421fe8ad6a654ff080103a6bee249e85",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "location":{
                      "x":409,
                      "y":530},
                    "size":{
                      "width":187,
                      "height":71}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e7ea0207f8d5428bbf315e5ff5d17bc5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"421fe8ad6a654ff080103a6bee249e85",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "location":{
                          "x":409,
                          "y":530},
                        "size":{
                          "width":187,
                          "height":71}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 修复",
                              "objectsToFades":[{
                                  "objectPath":["421fe8ad6a654ff080103a6bee249e85"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/主界面/u6.png"}},
{
                  "id":"9a2f4877e0ab46df86a14d1277bf6524",
                  "label":"",
                  "parentDynamicPanel":"421fe8ad6a654ff080103a6bee249e85",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "opacity":"0.5",
                    "location":{
                      "x":64,
                      "y":186},
                    "size":{
                      "width":96,
                      "height":96},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF66FF00}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2115ceb7c008467ca76f13025f3d5c17",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"421fe8ad6a654ff080103a6bee249e85",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "opacity":"0.5",
                        "location":{
                          "x":64,
                          "y":186},
                        "size":{
                          "width":96,
                          "height":96},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF66FF00}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/主角（暂停使用）/u14.png"}},
{
                  "id":"3dd6633878c844dda04bbf2e79971389",
                  "label":"",
                  "parentDynamicPanel":"421fe8ad6a654ff080103a6bee249e85",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":36,
                      "y":126},
                    "size":{
                      "width":221,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c4e627c1d31e4813bbc9c7e64862ec58",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"421fe8ad6a654ff080103a6bee249e85",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":36,
                          "y":126},
                        "size":{
                          "width":221,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5838d19c72554e13a0a98d51a3134eaa",
                  "label":"",
                  "parentDynamicPanel":"421fe8ad6a654ff080103a6bee249e85",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":30,
                      "y":160},
                    "size":{
                      "width":560,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/飞船/u53_line.png"}},
{
                  "id":"66c588e5bf4c46a78cec2f307d44a162",
                  "label":"",
                  "parentDynamicPanel":"421fe8ad6a654ff080103a6bee249e85",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "opacity":"0.5",
                    "location":{
                      "x":64,
                      "y":456},
                    "size":{
                      "width":96,
                      "height":96},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF66FF00}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bb0278dd6d2549a586fdbeab03979bdf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"421fe8ad6a654ff080103a6bee249e85",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "opacity":"0.5",
                        "location":{
                          "x":64,
                          "y":456},
                        "size":{
                          "width":96,
                          "height":96},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF66FF00}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/主角（暂停使用）/u14.png"}},
{
                  "id":"0b29261f35d44e5796f2d370438f1387",
                  "label":"",
                  "parentDynamicPanel":"421fe8ad6a654ff080103a6bee249e85",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "opacity":"0.5",
                    "location":{
                      "x":464,
                      "y":186},
                    "size":{
                      "width":96,
                      "height":96},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF66FF00}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8423aeb2f1a44553bbfe97041baa4384",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"421fe8ad6a654ff080103a6bee249e85",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "opacity":"0.5",
                        "location":{
                          "x":464,
                          "y":186},
                        "size":{
                          "width":96,
                          "height":96},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF66FF00}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/主角（暂停使用）/u14.png"}},
{
                  "id":"d731f8081ebf41e5b601358a1b91f448",
                  "label":"",
                  "parentDynamicPanel":"421fe8ad6a654ff080103a6bee249e85",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":265,
                      "y":279.588897705078},
                    "size":{
                      "width":105,
                      "height":147},
                    "rotation":"232",
                    "textRotation":"232",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"869a753b737a4058bcac10ee4d1442a9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"421fe8ad6a654ff080103a6bee249e85",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":265,
                          "y":279.588897705078},
                        "size":{
                          "width":105,
                          "height":147},
                        "rotation":"232",
                        "textRotation":"232",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/飞船/u80.png"}},
{
                  "id":"6e2e6984523b4665ad0f89cadf9ff1bd",
                  "label":"",
                  "parentDynamicPanel":"421fe8ad6a654ff080103a6bee249e85",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":217.491668701172,
                      "y":402.832244873047},
                    "size":{
                      "width":26,
                      "height":33},
                    "rotation":"330",
                    "textRotation":"330"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7eba2995ccbc4e49b5c241ca3f1c89c3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"421fe8ad6a654ff080103a6bee249e85",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":217.491668701172,
                          "y":402.832244873047},
                        "size":{
                          "width":26,
                          "height":33},
                        "rotation":"330",
                        "textRotation":"330"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/飞船/u82.png"}},
{
                  "id":"cdfbe0665ee54d2e9cc459b07ef05bee",
                  "label":"",
                  "parentDynamicPanel":"421fe8ad6a654ff080103a6bee249e85",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":227.859649658203,
                      "y":272.640350341797},
                    "size":{
                      "width":26,
                      "height":33},
                    "rotation":"45",
                    "textRotation":"45"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"93abe77bd184473bb158e37d57398455",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"421fe8ad6a654ff080103a6bee249e85",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":227.859649658203,
                          "y":272.640350341797},
                        "size":{
                          "width":26,
                          "height":33},
                        "rotation":"45",
                        "textRotation":"45"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/飞船/u82.png"}},
{
                  "id":"b2abb1ee3fa64e53aa6b608c2ac31c9a",
                  "label":"",
                  "parentDynamicPanel":"421fe8ad6a654ff080103a6bee249e85",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":387,
                      "y":283},
                    "size":{
                      "width":26,
                      "height":33},
                    "rotation":"135",
                    "textRotation":"135"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cae31931e7174033ba12a1e1be36d1f8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"421fe8ad6a654ff080103a6bee249e85",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":387,
                          "y":283},
                        "size":{
                          "width":26,
                          "height":33},
                        "rotation":"135",
                        "textRotation":"135"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/飞船/u82.png"}},
{
                  "id":"624d4544c1374f07bbffa1a6a09025dc",
                  "label":"",
                  "parentDynamicPanel":"421fe8ad6a654ff080103a6bee249e85",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":392,
                      "y":261},
                    "size":{
                      "width":84,
                      "height":10},
                    "rotation":"135",
                    "borderWidth":"5"},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/飞船/u88_line.png"}},
{
                  "id":"f021671b760745229b162f377c25b6b9",
                  "label":"",
                  "parentDynamicPanel":"421fe8ad6a654ff080103a6bee249e85",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":166,
                      "y":250},
                    "size":{
                      "width":84,
                      "height":10},
                    "rotation":"45",
                    "borderWidth":"5"},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/飞船/u88_line.png"}},
{
                  "id":"1a736c0f0dfd422697a6721171b00ed0",
                  "label":"",
                  "parentDynamicPanel":"421fe8ad6a654ff080103a6bee249e85",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":162,
                      "y":432},
                    "size":{
                      "width":68,
                      "height":10},
                    "rotation":"330",
                    "borderWidth":"5"},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/飞船/u90_line.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "d476c9cd7cb74d1bbaa44ea524ce45be":{
      "scriptId":"u0"},
    "691cdfc1b5e340eab9a6f1a1f02f2798":{
      "scriptId":"u1"},
    "d3eb9f29f6c24c1e9b1430bff20f0fa5":{
      "scriptId":"u2"},
    "cf6636e0ed0e480da7b62052b263b4df":{
      "scriptId":"u3"},
    "00bc3c558e814917a614c0889b9ffbf6":{
      "scriptId":"u4"},
    "935f887ec13f4dcab44a40141d0097ae":{
      "scriptId":"u5"},
    "25b97b0cc68446eab61b204ebdbe6b7a":{
      "scriptId":"u6"},
    "609ed00ac86e441c8ab5d48ea40e2f7f":{
      "scriptId":"u7"},
    "66748ae8e45e4d7bae5188a62d60da01":{
      "scriptId":"u8"},
    "2435466568c041119a380e04360e9209":{
      "scriptId":"u9"},
    "746a20de6e2a4dc7afd86573bab1a9ac":{
      "scriptId":"u10"},
    "8d7c24f577f14ad18f158eadb7ac791a":{
      "scriptId":"u11"},
    "91a3351ca7d141c9a70623bcc886e560":{
      "scriptId":"u12"},
    "e73295ad94d2401381d520cf65208427":{
      "scriptId":"u13"},
    "acb970ee20784209bab9db94dfe70938":{
      "scriptId":"u14"},
    "deb000cdcc974023b44ce3d6a3386871":{
      "scriptId":"u15"},
    "04f93bc9a676484f8766eb5d8555fac6":{
      "scriptId":"u16"},
    "9a7a53eec2c64bf4b8941fe4b987cb7d":{
      "scriptId":"u17"},
    "f2a607466597463990d4419597a72064":{
      "scriptId":"u18"},
    "b5673377a5334bcbbe4d36c5931b8460":{
      "scriptId":"u19"},
    "ca1d8b686d1d4d47a7b1f68c1a39316d":{
      "scriptId":"u20"},
    "2a8d3d55cea749bf9fb7b90991f48e5a":{
      "scriptId":"u21"},
    "6bbdabc8de694a5080109e114dff0361":{
      "scriptId":"u22"},
    "8960deb34aec45fdbd19ba8648723fde":{
      "scriptId":"u23"},
    "4e1decc8d1eb41778ccdbedb65dbf0a7":{
      "scriptId":"u24"},
    "2525746bdaf84be3974b4b92ae3c8d3b":{
      "scriptId":"u25"},
    "a6bc64f957414258b824e79be2ad0087":{
      "scriptId":"u26"},
    "1958e028a46a452bbbd76b95ce401c08":{
      "scriptId":"u27"},
    "8ee2c66318c24386a8fa68a58b70fff2":{
      "scriptId":"u28"},
    "854052b4d76a4495a8984228429ddb95":{
      "scriptId":"u29"},
    "995b648e560743318b0bc35445a21b9b":{
      "scriptId":"u30"},
    "b11d5c58319c4f61af36334b927a8fbd":{
      "scriptId":"u31"},
    "3d16528b0efc487e87921d9e4db0c546":{
      "scriptId":"u32"},
    "57d8d85664f34775a03a02802a734fd3":{
      "scriptId":"u33"},
    "5a3c4552fb7749b1a948a7c61d14e0f8":{
      "scriptId":"u34"},
    "1924225e95e6462d9c200c31be09fe5c":{
      "scriptId":"u35"},
    "63c96283594e4f08b702a817533506c5":{
      "scriptId":"u36"},
    "db99165ac3aa40fdbf227aea3895ae2f":{
      "scriptId":"u37"},
    "b9b5df246f5d4a1380c7b840d70dd37f":{
      "scriptId":"u38"},
    "68b2f091d0f9426f99691fbbc2c390a9":{
      "scriptId":"u39"},
    "7b32ebda2c274a818eb812d6bd1c3843":{
      "scriptId":"u40"},
    "df5180a2f5614effb9da7dd7162c619b":{
      "scriptId":"u41"},
    "4eca187903d8462f880d95e5ab4eda51":{
      "scriptId":"u42"},
    "cb32f5e95b4f41b78d9eb3d797137240":{
      "scriptId":"u43"},
    "4ca28912140f49c6925e1da43b55698e":{
      "scriptId":"u44"},
    "eb12d0516faf4e55a6b58c703127a2ce":{
      "scriptId":"u45"},
    "22bd5f1d2f5440f6b96e6586d263d7c3":{
      "scriptId":"u46"},
    "8e3cbdb03aca4e17b19fedbf79f4e800":{
      "scriptId":"u47"},
    "469562963ed34f93b1a7f8de43272d0d":{
      "scriptId":"u48"},
    "af73f95cbfe640c79d011dabf6b9685a":{
      "scriptId":"u49"},
    "fb7f7837a69d41b8b51a73a472b57fde":{
      "scriptId":"u50"},
    "acde07733d314475bd1ee81bde7c58d1":{
      "scriptId":"u51"},
    "8ef2c976aad34bb7b2cd11a1145b78ed":{
      "scriptId":"u52"},
    "900499f9d6d14da0a8a5388c5d7f5de6":{
      "scriptId":"u53"},
    "7311be73b7594f03b8052687097dcee2":{
      "scriptId":"u54"},
    "96ee00d2c4494fe2af32acd43f3f91fb":{
      "scriptId":"u55"},
    "6af37a4c4d3a4a2f9453b491c577e171":{
      "scriptId":"u56"},
    "81d38a038b06497c91566ca836f5873c":{
      "scriptId":"u57"},
    "e5d02933b0724b09bbd3c5130e8c1134":{
      "scriptId":"u58"},
    "c91ead941ab6493594015ceaa0b3cc17":{
      "scriptId":"u59"},
    "421fe8ad6a654ff080103a6bee249e85":{
      "scriptId":"u60"},
    "1d5d139f133148518d59cab5bfac4f29":{
      "scriptId":"u61"},
    "4c61a572d9cc4362b45bc3f908ab895d":{
      "scriptId":"u62"},
    "8d798a124cd6403aae062a4ee9a0e602":{
      "scriptId":"u63"},
    "343e807d4ad341988218d07722bc5a07":{
      "scriptId":"u64"},
    "51ff473ba75e499ab122485659662efc":{
      "scriptId":"u65"},
    "541b5dc4429a42628939a15021596ccf":{
      "scriptId":"u66"},
    "fe4b31be59634f128eedf4e8b358e7f0":{
      "scriptId":"u67"},
    "ca274b280c5d4838ae4e039d5cffb974":{
      "scriptId":"u68"},
    "a122b365e5784abb97f496545a3d25c9":{
      "scriptId":"u69"},
    "e7ea0207f8d5428bbf315e5ff5d17bc5":{
      "scriptId":"u70"},
    "9a2f4877e0ab46df86a14d1277bf6524":{
      "scriptId":"u71"},
    "2115ceb7c008467ca76f13025f3d5c17":{
      "scriptId":"u72"},
    "3dd6633878c844dda04bbf2e79971389":{
      "scriptId":"u73"},
    "c4e627c1d31e4813bbc9c7e64862ec58":{
      "scriptId":"u74"},
    "5838d19c72554e13a0a98d51a3134eaa":{
      "scriptId":"u75"},
    "66c588e5bf4c46a78cec2f307d44a162":{
      "scriptId":"u76"},
    "bb0278dd6d2549a586fdbeab03979bdf":{
      "scriptId":"u77"},
    "0b29261f35d44e5796f2d370438f1387":{
      "scriptId":"u78"},
    "8423aeb2f1a44553bbfe97041baa4384":{
      "scriptId":"u79"},
    "d731f8081ebf41e5b601358a1b91f448":{
      "scriptId":"u80"},
    "869a753b737a4058bcac10ee4d1442a9":{
      "scriptId":"u81"},
    "6e2e6984523b4665ad0f89cadf9ff1bd":{
      "scriptId":"u82"},
    "7eba2995ccbc4e49b5c241ca3f1c89c3":{
      "scriptId":"u83"},
    "cdfbe0665ee54d2e9cc459b07ef05bee":{
      "scriptId":"u84"},
    "93abe77bd184473bb158e37d57398455":{
      "scriptId":"u85"},
    "b2abb1ee3fa64e53aa6b608c2ac31c9a":{
      "scriptId":"u86"},
    "cae31931e7174033ba12a1e1be36d1f8":{
      "scriptId":"u87"},
    "624d4544c1374f07bbffa1a6a09025dc":{
      "scriptId":"u88"},
    "f021671b760745229b162f377c25b6b9":{
      "scriptId":"u89"},
    "1a736c0f0dfd422697a6721171b00ed0":{
      "scriptId":"u90"}}});