$axure.loadCurrentPage({
  "url":"副本.html",
  "generationDate":new Date(1491376836352.89),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"opentype"],
  "page":{
    "packageId":"29a4acf324c34b5f99cdd108ba0f38f3",
    "type":"Axure:Page",
    "name":"副本",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2896126eb63845d18716c4527b7cd8dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":20,
              "y":35},
            "size":{
              "width":734,
              "height":1295}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a7b4815be054d2f9c925238a296c443",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":20,
                  "y":35},
                "size":{
                  "width":734,
                  "height":1295}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u0.png"}},
{
          "id":"1f2358750fe44efa89013636115adc92",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":27,
              "y":43},
            "size":{
              "width":720,
              "height":1280}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"667da75818eb4c52a66160e8aa6b6061",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":27,
                  "y":43},
                "size":{
                  "width":720,
                  "height":1280}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u2.png"}},
{
          "id":"6ccb228197b54bc3b0847c69bd74cf77",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":274,
              "y":800},
            "size":{
              "width":91,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"736c1bd789444133ab5b9c1394fda7e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":274,
                  "y":800},
                "size":{
                  "width":91,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u4.png"}},
{
          "id":"9257e0aa6cd84b1583ce02752fb2760f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":38,
              "y":1244},
            "size":{
              "width":161,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bdc246d4bc147e9bc4034b183e853f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":38,
                  "y":1244},
                "size":{
                  "width":161,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"9df34c6ae2524b7eb8d2d00f78c6fe6d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":388,
              "y":1244},
            "size":{
              "width":161,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d440ed588df54e3ba3268e732c5edc56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":388,
                  "y":1244},
                "size":{
                  "width":161,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"e68112769ae848cc897fe0439633db59",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":550,
              "y":1050},
            "size":{
              "width":91,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e140a1bca3040928ba02738a72e30dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":550,
                  "y":1050},
                "size":{
                  "width":91,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"1cd20c41c55b4cae9c5d623e174aecd4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":563,
              "y":1244},
            "size":{
              "width":161,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1f1a9a2153b4d788adcf2a53973d052",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":563,
                  "y":1244},
                "size":{
                  "width":161,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"4be137c4cc9e4a0e949763c7bc795089",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":84,
              "y":68},
            "size":{
              "width":254,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16651a4498de4a28abf12d9d18fee1d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":84,
                  "y":68},
                "size":{
                  "width":254,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u14.png"}},
{
          "id":"fe9d438ed1ed45899f404882275e70fc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":56,
              "y":68},
            "size":{
              "width":55,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66ba89d1815e4302bd3bbba45b582da3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":56,
                  "y":68},
                "size":{
                  "width":55,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u16.png"}},
{
          "id":"0825ba23e58c40cca860becafbfba028",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":298,
              "y":60},
            "size":{
              "width":67,
              "height":68}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccbca00f14d24f3aa12fd2fce05b658a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":298,
                  "y":60},
                "size":{
                  "width":67,
                  "height":68}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u18.png"}},
{
          "id":"390d6f209c92428e816424c1bd813702",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":438,
              "y":68},
            "size":{
              "width":254,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae6cb635b5a8489c981606efaad7c289",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":438,
                  "y":68},
                "size":{
                  "width":254,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u14.png"}},
{
          "id":"d4d1115af37446dcb2489e2a85d2b7ef",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":408,
              "y":68},
            "size":{
              "width":55,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e9c149598954583a6522676f3eee18a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":408,
                  "y":68},
                "size":{
                  "width":55,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u22.png"}},
{
          "id":"2ce73ccd580c4cc3931b62306f5ed2da",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":651,
              "y":62},
            "size":{
              "width":67,
              "height":68}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"141cb4bc9ff84e30abdde482a8060644",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":651,
                  "y":62},
                "size":{
                  "width":67,
                  "height":68}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u18.png"}},
{
          "id":"d6bc05c288fb4d9e9f19f410bedd0435",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":462,
              "y":750},
            "size":{
              "width":138,
              "height":83}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a3d08e65ef94b6181f42e696989c7a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":462,
                  "y":750},
                "size":{
                  "width":138,
                  "height":83}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"ca29886320cf40e4ab757d488f23afb7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":462,
              "y":340},
            "size":{
              "width":160,
              "height":83}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4e8c02202784da282a2301c4b8056dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":462,
                  "y":340},
                "size":{
                  "width":160,
                  "height":83}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"de1afaab202d4ae59cafa1227892584f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":53,
              "y":1050},
            "size":{
              "width":110,
              "height":83}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"322411ee4fdd43f6a50640bae4416a6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":53,
                  "y":1050},
                "size":{
                  "width":110,
                  "height":83}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"38a57721c4b04ffb9cc5156470908177",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":53,
              "y":390},
            "size":{
              "width":204,
              "height":83}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93ae1c533e73476ca11312effcad17a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":53,
                  "y":390},
                "size":{
                  "width":204,
                  "height":83}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"aa8fa805a802496c9fe6ee54733e11ae",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":408,
              "y":550},
            "size":{
              "width":204,
              "height":83}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d1e355b3c0e4908a016f673b62cbaf1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":408,
                  "y":550},
                "size":{
                  "width":204,
                  "height":83}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"d109443eb80a4c9fa11dcd44b4d023c5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":156,
              "y":657},
            "size":{
              "width":88,
              "height":83}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1e6fdf9a4d4401795d7aba61c083330",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":156,
                  "y":657},
                "size":{
                  "width":88,
                  "height":83}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"83773b175b9d4dcdbf47f827a7b08e31",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":151,
              "y":190},
            "size":{
              "width":120,
              "height":83}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a62549ae83f426caa36a73b71fcabf4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":151,
                  "y":190},
                "size":{
                  "width":120,
                  "height":83}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"4f1e753c142c40688ba91da0f8b950ef",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":213,
              "y":1244},
            "size":{
              "width":161,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ec43bf1a94d4bd988b9f5a0e0201348",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":213,
                  "y":1244},
                "size":{
                  "width":161,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"a302cff2a18a40939bf182761aa5635c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":38,
              "y":537},
            "size":{
              "width":110,
              "height":83}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b8faa4742284c1799a22a4597d8f584",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":38,
                  "y":537},
                "size":{
                  "width":110,
                  "height":83}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"b6bbaa0f5a4f4e2fa172a58a2fe689bc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":637,
              "y":897},
            "size":{
              "width":110,
              "height":83}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"441f5603f8cb43c683b09d9807345b53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":637,
                  "y":897},
                "size":{
                  "width":110,
                  "height":83}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"a037c69227a649388eb07786a51ccd02",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "opacity":"0.75",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":27,
              "y":42},
            "size":{
              "width":720,
              "height":1281},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e77a42b26a944ce8408d0b14b1b688d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.75",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":27,
                  "y":42},
                "size":{
                  "width":720,
                  "height":1281},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/副本/u46.png"}},
{
          "id":"ede2c31a511c4d0899bc84c8547e298e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":483},
            "size":{
              "width":686,
              "height":497}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71cc066024d84d18afc0430197ad570e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":483},
                "size":{
                  "width":686,
                  "height":497}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/副本/u48.png"}},
{
          "id":"bbb7517765884b58a82bc9ac2299007c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":641,
              "y":422},
            "size":{
              "width":102,
              "height":98}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d95f8f27b774f87a605ca2a4fa89a61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":641,
                  "y":422},
                "size":{
                  "width":102,
                  "height":98}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主界面",
                      "target":{
                        "targetType":"page",
                        "url":"主界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/副本/u50.png"}},
{
          "id":"cd2cb56750ae4e7e9e30f1e9cd83f4b1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":57,
              "y":614},
            "size":{
              "width":289,
              "height":214},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000},
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3a69765910e43f38301b16a81ac7d90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":57,
                  "y":614},
                "size":{
                  "width":289,
                  "height":214},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/副本/u52.png"}},
{
          "id":"eb959667505148f0a5b746a52380332b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":57,
              "y":614},
            "size":{
              "width":289,
              "height":214},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35feb673e1aa41099abceb52d4a87b55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":57,
                  "y":614},
                "size":{
                  "width":289,
                  "height":214},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/副本/u54.png"}},
{
          "id":"855fa03545414ef182c40c76be52dcff",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":415,
              "y":614},
            "size":{
              "width":289,
              "height":214},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000},
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cf92825b0724b90827fdad8c9b9f9db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":415,
                  "y":614},
                "size":{
                  "width":289,
                  "height":214},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/副本/u52.png"}},
{
          "id":"dbb41edbf6c743be88628a566c6a787e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":415,
              "y":614},
            "size":{
              "width":289,
              "height":214},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d73ee12efbf407e81edc2ea017ae0db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":415,
                  "y":614},
                "size":{
                  "width":289,
                  "height":214},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/副本/u54.png"}},
{
          "id":"ca5bc75a1f54461e8f541ea3fa3226c2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":514,
              "y":670},
            "size":{
              "width":90,
              "height":102}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b75754e2cbd4f7a9027e6b2a35c5b29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":514,
                  "y":670},
                "size":{
                  "width":90,
                  "height":102}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/副本/u60.png"}},
{
          "id":"ba5bfc6908a8481ba8f3251b6cd08898",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":188,
              "y":578.5},
            "size":{
              "width":386,
              "height":285},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000},
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fa2caa5b0f049618dfe45e6320b08a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":188,
                  "y":578.5},
                "size":{
                  "width":386,
                  "height":285},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/副本/u62.png"}},
{
          "id":"9366a842ae054b5a9932d83714b78552",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":455},
            "size":{
              "width":309,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac4481883b2649b8b755d21a2d16dfd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":455},
                "size":{
                  "width":309,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/副本/u64.png"}},
{
          "id":"21c6815adc5349d58a778b91fe681b6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":330,
              "y":460},
            "size":{
              "width":113,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a853555789c48d29a0b0efb0a5418dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":330,
                  "y":460},
                "size":{
                  "width":113,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78e2b816beca40809823e67ee2ec42d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "opacity":"0.75",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":188,
              "y":813},
            "size":{
              "width":386,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0d3feedc2fe4740b6e458edb9f5a22d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.75",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":188,
                  "y":813},
                "size":{
                  "width":386,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/副本/u68.png"}},
{
          "id":"e47a69f7a6904be09249464ba5cdf906",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":332,
              "y":808},
            "size":{
              "width":85,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f57075fbd06843d48b87fc72aa8e1f6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":332,
                  "y":808},
                "size":{
                  "width":85,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fa34be8fcda242769641fdb95795c6e9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":263,
              "y":882},
            "size":{
              "width":223,
              "height":58}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1e21553b55c45299e4e1fa225886e10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":263,
                  "y":882},
                "size":{
                  "width":223,
                  "height":58}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 loading",
                      "target":{
                        "targetType":"page",
                        "url":"loading.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主界面/u6.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "2896126eb63845d18716c4527b7cd8dd":{
      "scriptId":"u0"},
    "7a7b4815be054d2f9c925238a296c443":{
      "scriptId":"u1"},
    "1f2358750fe44efa89013636115adc92":{
      "scriptId":"u2"},
    "667da75818eb4c52a66160e8aa6b6061":{
      "scriptId":"u3"},
    "6ccb228197b54bc3b0847c69bd74cf77":{
      "scriptId":"u4"},
    "736c1bd789444133ab5b9c1394fda7e1":{
      "scriptId":"u5"},
    "9257e0aa6cd84b1583ce02752fb2760f":{
      "scriptId":"u6"},
    "4bdc246d4bc147e9bc4034b183e853f8":{
      "scriptId":"u7"},
    "9df34c6ae2524b7eb8d2d00f78c6fe6d":{
      "scriptId":"u8"},
    "d440ed588df54e3ba3268e732c5edc56":{
      "scriptId":"u9"},
    "e68112769ae848cc897fe0439633db59":{
      "scriptId":"u10"},
    "2e140a1bca3040928ba02738a72e30dd":{
      "scriptId":"u11"},
    "1cd20c41c55b4cae9c5d623e174aecd4":{
      "scriptId":"u12"},
    "b1f1a9a2153b4d788adcf2a53973d052":{
      "scriptId":"u13"},
    "4be137c4cc9e4a0e949763c7bc795089":{
      "scriptId":"u14"},
    "16651a4498de4a28abf12d9d18fee1d6":{
      "scriptId":"u15"},
    "fe9d438ed1ed45899f404882275e70fc":{
      "scriptId":"u16"},
    "66ba89d1815e4302bd3bbba45b582da3":{
      "scriptId":"u17"},
    "0825ba23e58c40cca860becafbfba028":{
      "scriptId":"u18"},
    "ccbca00f14d24f3aa12fd2fce05b658a":{
      "scriptId":"u19"},
    "390d6f209c92428e816424c1bd813702":{
      "scriptId":"u20"},
    "ae6cb635b5a8489c981606efaad7c289":{
      "scriptId":"u21"},
    "d4d1115af37446dcb2489e2a85d2b7ef":{
      "scriptId":"u22"},
    "8e9c149598954583a6522676f3eee18a":{
      "scriptId":"u23"},
    "2ce73ccd580c4cc3931b62306f5ed2da":{
      "scriptId":"u24"},
    "141cb4bc9ff84e30abdde482a8060644":{
      "scriptId":"u25"},
    "d6bc05c288fb4d9e9f19f410bedd0435":{
      "scriptId":"u26"},
    "2a3d08e65ef94b6181f42e696989c7a2":{
      "scriptId":"u27"},
    "ca29886320cf40e4ab757d488f23afb7":{
      "scriptId":"u28"},
    "b4e8c02202784da282a2301c4b8056dc":{
      "scriptId":"u29"},
    "de1afaab202d4ae59cafa1227892584f":{
      "scriptId":"u30"},
    "322411ee4fdd43f6a50640bae4416a6f":{
      "scriptId":"u31"},
    "38a57721c4b04ffb9cc5156470908177":{
      "scriptId":"u32"},
    "93ae1c533e73476ca11312effcad17a7":{
      "scriptId":"u33"},
    "aa8fa805a802496c9fe6ee54733e11ae":{
      "scriptId":"u34"},
    "5d1e355b3c0e4908a016f673b62cbaf1":{
      "scriptId":"u35"},
    "d109443eb80a4c9fa11dcd44b4d023c5":{
      "scriptId":"u36"},
    "e1e6fdf9a4d4401795d7aba61c083330":{
      "scriptId":"u37"},
    "83773b175b9d4dcdbf47f827a7b08e31":{
      "scriptId":"u38"},
    "4a62549ae83f426caa36a73b71fcabf4":{
      "scriptId":"u39"},
    "4f1e753c142c40688ba91da0f8b950ef":{
      "scriptId":"u40"},
    "5ec43bf1a94d4bd988b9f5a0e0201348":{
      "scriptId":"u41"},
    "a302cff2a18a40939bf182761aa5635c":{
      "scriptId":"u42"},
    "5b8faa4742284c1799a22a4597d8f584":{
      "scriptId":"u43"},
    "b6bbaa0f5a4f4e2fa172a58a2fe689bc":{
      "scriptId":"u44"},
    "441f5603f8cb43c683b09d9807345b53":{
      "scriptId":"u45"},
    "a037c69227a649388eb07786a51ccd02":{
      "scriptId":"u46"},
    "8e77a42b26a944ce8408d0b14b1b688d":{
      "scriptId":"u47"},
    "ede2c31a511c4d0899bc84c8547e298e":{
      "scriptId":"u48"},
    "71cc066024d84d18afc0430197ad570e":{
      "scriptId":"u49"},
    "bbb7517765884b58a82bc9ac2299007c":{
      "scriptId":"u50"},
    "7d95f8f27b774f87a605ca2a4fa89a61":{
      "scriptId":"u51"},
    "cd2cb56750ae4e7e9e30f1e9cd83f4b1":{
      "scriptId":"u52"},
    "c3a69765910e43f38301b16a81ac7d90":{
      "scriptId":"u53"},
    "eb959667505148f0a5b746a52380332b":{
      "scriptId":"u54"},
    "35feb673e1aa41099abceb52d4a87b55":{
      "scriptId":"u55"},
    "855fa03545414ef182c40c76be52dcff":{
      "scriptId":"u56"},
    "7cf92825b0724b90827fdad8c9b9f9db":{
      "scriptId":"u57"},
    "dbb41edbf6c743be88628a566c6a787e":{
      "scriptId":"u58"},
    "7d73ee12efbf407e81edc2ea017ae0db":{
      "scriptId":"u59"},
    "ca5bc75a1f54461e8f541ea3fa3226c2":{
      "scriptId":"u60"},
    "4b75754e2cbd4f7a9027e6b2a35c5b29":{
      "scriptId":"u61"},
    "ba5bfc6908a8481ba8f3251b6cd08898":{
      "scriptId":"u62"},
    "8fa2caa5b0f049618dfe45e6320b08a4":{
      "scriptId":"u63"},
    "9366a842ae054b5a9932d83714b78552":{
      "scriptId":"u64"},
    "ac4481883b2649b8b755d21a2d16dfd0":{
      "scriptId":"u65"},
    "21c6815adc5349d58a778b91fe681b6b":{
      "scriptId":"u66"},
    "8a853555789c48d29a0b0efb0a5418dd":{
      "scriptId":"u67"},
    "78e2b816beca40809823e67ee2ec42d0":{
      "scriptId":"u68"},
    "d0d3feedc2fe4740b6e458edb9f5a22d":{
      "scriptId":"u69"},
    "e47a69f7a6904be09249464ba5cdf906":{
      "scriptId":"u70"},
    "f57075fbd06843d48b87fc72aa8e1f6d":{
      "scriptId":"u71"},
    "fa34be8fcda242769641fdb95795c6e9":{
      "scriptId":"u72"},
    "c1e21553b55c45299e4e1fa225886e10":{
      "scriptId":"u73"}}});