$axure.loadCurrentPage({
  "url":"药品.html",
  "generationDate":new Date(1477979555274.91),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"58c9043831174239abaa8467913eade4",
    "type":"Axure:Page",
    "name":"药品",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"aee9a39dff414dac92cb6f314479dfec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":20,
              "y":35},
            "size":{
              "width":734,
              "height":1295}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0749b93143744cdfa3d378e277a17b62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":20,
                  "y":35},
                "size":{
                  "width":734,
                  "height":1295}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u0.png"}},
{
          "id":"ce40f3fd2d8a4cc382f14c93d741e731",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":27,
              "y":43},
            "size":{
              "width":720,
              "height":1280}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"540ad177143a4f689d11e7a27bf0b887",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":27,
                  "y":43},
                "size":{
                  "width":720,
                  "height":1280}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u2.png"}},
{
          "id":"ca05e1de32f04f1793cbf90001deed61",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":44,
              "y":105},
            "size":{
              "width":680,
              "height":1190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e327bf63daf94ac9a579d5c42ab98519",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":44,
                  "y":105},
                "size":{
                  "width":680,
                  "height":1190}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u4.png"}},
{
          "id":"858abfe2560f4e82b95c29a6841800b6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":645,
              "y":47},
            "size":{
              "width":102,
              "height":98}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49b7b2a51c354cb48faabf10542eaefe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":645,
                  "y":47},
                "size":{
                  "width":102,
                  "height":98}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主界面",
                      "target":{
                        "targetType":"page",
                        "url":"主界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/副本/u42.png"}},
{
          "id":"2711342c5180499995a2184dc2b8d754",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":64,
              "y":1130},
            "size":{
              "width":636,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/付费/u18_line.png"}},
{
          "id":"4221d184b638443d9f072ad65f4ce7e5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":68,
              "y":950},
            "size":{
              "width":635,
              "height":319}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29affc9e389d42c9a2fac89da45c9625",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":68,
                  "y":950},
                "size":{
                  "width":635,
                  "height":319}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药品/u9.png"}},
{
          "id":"1ad79e2cccc44bc68aceb6ad591fb132",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":68,
              "y":201},
            "size":{
              "width":635,
              "height":729}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"849f63b671ba4ffba11eebf6845fd8bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":68,
                  "y":201},
                "size":{
                  "width":635,
                  "height":729}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药品/u11.png"}},
{
          "id":"08e01afcefff4519ae724d32033aa04f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":102,
              "y":362},
            "size":{
              "width":132,
              "height":134}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45166b8ad4504279bf47cf403f73d97d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":102,
                  "y":362},
                "size":{
                  "width":132,
                  "height":134}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/装备/u43.png"}},
{
          "id":"ad73b02a9d5b4ee1962c67b2e3a82a72",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":88,
              "y":664},
            "size":{
              "width":589,
              "height":149}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e5dcdaa59764b658fd19c98c13b64a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":88,
                  "y":664},
                "size":{
                  "width":589,
                  "height":149}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药品/u15.png"}},
{
          "id":"e6fff608ad0947ebbdeb09b36af0f8b7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":88,
              "y":648},
            "size":{
              "width":160,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a96670bcffe4daab28ba1a4b6f0ed53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":88,
                  "y":648},
                "size":{
                  "width":160,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药品/u17.png"}},
{
          "id":"fd7724ac30af4b7b91c0ae278fbfc21e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":100,
              "y":710},
            "size":{
              "width":560,
              "height":85}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ea408e8cc4a44029af2efc3a22b8b04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":100,
                  "y":710},
                "size":{
                  "width":560,
                  "height":85}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4729db1aad9c4c6f8f3b483b12408d2c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":348,
              "y":236},
            "size":{
              "width":97,
              "height":98}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61a828199cb34e779d01d2b49d20da9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":348,
                  "y":236},
                "size":{
                  "width":97,
                  "height":98}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药品/u21.png"}},
{
          "id":"8bb89f96edd54a9bbab7e0bc58d4c7df",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":384,
              "y":823},
            "size":{
              "width":276,
              "height":83}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24f9312cab4349e78f6ff2a23e6ffeeb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":384,
                  "y":823},
                "size":{
                  "width":276,
                  "height":83}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"9c2e08d8f183454b84f19bd4a54deec8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":348,
              "y":380},
            "size":{
              "width":97,
              "height":98}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f1d82d2e7c74199a181c3869bf6548e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":348,
                  "y":380},
                "size":{
                  "width":97,
                  "height":98}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药品/u21.png"}},
{
          "id":"ffc25fc19dee4256af8dbe34373cfc4d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":348,
              "y":524},
            "size":{
              "width":97,
              "height":98}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3dedc03daf794c4c843cc24a2e806ccc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":348,
                  "y":524},
                "size":{
                  "width":97,
                  "height":98}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药品/u21.png"}},
{
          "id":"67c1ec8679ee4deba30465f089f1c361",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":234,
              "y":424},
            "size":{
              "width":114,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/药品/u29_line.png"}},
{
          "id":"81249983357943f8b7bee54b3c4b88ce",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":280},
            "size":{
              "width":48,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/药品/u30_line.png"}},
{
          "id":"c4ba490c8bab455b92ec957f7d45bf07",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":568},
            "size":{
              "width":48,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/药品/u30_line.png"}},
{
          "id":"ab350897e95b4fb3985b1006f7489c1b",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":280},
            "size":{
              "width":10,
              "height":298}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/药品/u32_line.png"}},
{
          "id":"8a717738154f4cd685c681e0958db3fb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.25",
            "location":{
              "x":455,
              "y":236},
            "size":{
              "width":222,
              "height":43},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF66FF00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22125141d0794e939722241ccb94e489",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.25",
                "location":{
                  "x":455,
                  "y":236},
                "size":{
                  "width":222,
                  "height":43},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药品/u33.png"}},
{
          "id":"5a5062a87a6547a6b9d51a107c1e3123",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":470,
              "y":245},
            "size":{
              "width":141,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ec15006ced541488395e6ef25c8b394",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":470,
                  "y":245},
                "size":{
                  "width":141,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c42aecbf0474bae9940f2d543bc82c3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.25",
            "location":{
              "x":455,
              "y":287},
            "size":{
              "width":222,
              "height":43},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF66FF00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81ac31ba1b2c4102a3f7dce3e6ef4afd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.25",
                "location":{
                  "x":455,
                  "y":287},
                "size":{
                  "width":222,
                  "height":43},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药品/u33.png"}},
{
          "id":"3d0a9772bbed4d89ab8f0c8a21cf4f8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":470,
              "y":296},
            "size":{
              "width":141,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd6a1928713b494cae572a8551acc6df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":470,
                  "y":296},
                "size":{
                  "width":141,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9b2c65ce9b034325bf566db5952be560",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.25",
            "location":{
              "x":455,
              "y":382},
            "size":{
              "width":222,
              "height":43},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF66FF00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"474dee83150a4dd1b620434c725894fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.25",
                "location":{
                  "x":455,
                  "y":382},
                "size":{
                  "width":222,
                  "height":43},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药品/u33.png"}},
{
          "id":"048b0e481d584a98bdb3027d4d063efe",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":470,
              "y":391},
            "size":{
              "width":141,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c307cad7d7648d3b7ed74eedf1118be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":470,
                  "y":391},
                "size":{
                  "width":141,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e5a56d7de004dfa821460f880ccc543",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.25",
            "location":{
              "x":455,
              "y":433},
            "size":{
              "width":222,
              "height":43},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF66FF00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71e6910abf91418ea16de6961eea0e17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.25",
                "location":{
                  "x":455,
                  "y":433},
                "size":{
                  "width":222,
                  "height":43},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药品/u33.png"}},
{
          "id":"9c17fe3bf6a84d959401429becf16c24",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":470,
              "y":442},
            "size":{
              "width":141,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a18e4f89269941388883ce17ac04e271",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":470,
                  "y":442},
                "size":{
                  "width":141,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3766313a19d84e5f828bde96fc866573",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.25",
            "location":{
              "x":455,
              "y":528},
            "size":{
              "width":222,
              "height":43},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF66FF00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eee7bc4ed9ef4fc4b7132263329739e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.25",
                "location":{
                  "x":455,
                  "y":528},
                "size":{
                  "width":222,
                  "height":43},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药品/u33.png"}},
{
          "id":"ef9c4bd202cd498e969073b379028c50",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":470,
              "y":537},
            "size":{
              "width":141,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe68914d24334aa6938b66e24aac4336",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":470,
                  "y":537},
                "size":{
                  "width":141,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df740d305a6c460e94553a224da7bdef",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.25",
            "location":{
              "x":455,
              "y":579},
            "size":{
              "width":222,
              "height":43},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF66FF00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb32ee4efbae4e73a855a90998ec9e34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.25",
                "location":{
                  "x":455,
                  "y":579},
                "size":{
                  "width":222,
                  "height":43},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药品/u33.png"}},
{
          "id":"f173805154d54efe93a1b3fb42d89e57",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":470,
              "y":588},
            "size":{
              "width":141,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70208235a7e9460aac3470c7ba6fc358",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":470,
                  "y":588},
                "size":{
                  "width":141,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b859f8b471e04e789e778d15d431d667",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":86,
              "y":834},
            "size":{
              "width":262,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61ff363048714dbda75ffa366f0875e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":86,
                  "y":834},
                "size":{
                  "width":262,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/装备/u34.png"}},
{
          "id":"5d726492821f43c6a55820682838b837",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":117,
              "y":842},
            "size":{
              "width":49,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"700d6eb4a4df4bb4a50cc8e1509b26e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":117,
                  "y":842},
                "size":{
                  "width":49,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u16.png"}},
{
          "id":"44358ee52ff64461a9a6600a32c8f213",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":161,
              "y":852},
            "size":{
              "width":170,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65f09164fec44e299a4a4f79e6bf3de4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":161,
                  "y":852},
                "size":{
                  "width":170,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"868fe7092f9b42c78d34631c923ae839",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":77,
              "y":980},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c498b825263345738ad2e9cbc9d1ecd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":77,
                  "y":980},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"ffb4e712e30c45dd807bd2e9c5b50cbf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":167,
              "y":980},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db477eb5a28c4ac78cca01c4e7a9410f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":167,
                  "y":980},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"e851e9b17188469e85fffc4cf5bd5bcc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":257,
              "y":980},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10c40e9557a74a7bac34a42026565ce3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":257,
                  "y":980},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"6eb7537c9ff3414895111acb74bd456e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":347,
              "y":980},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82da4490888c4f3f8d7134cc9b71d63e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":347,
                  "y":980},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"6cfbf233fc5f49b1a7b5ed3d49a65ab4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":436,
              "y":980},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64de5ff41dd94e8f881c1c2d320c3d34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":436,
                  "y":980},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"8894df23bb884cbda2ee5224aa7203f9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":526,
              "y":980},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"312504b78cb141c5a1e101a5dfafcf81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":526,
                  "y":980},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"d9abd75ed54243a9acac986415605ea4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":616,
              "y":980},
            "size":{
              "width":60,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF66FF00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"937f6cedb1d643ed949f17ba1b10f227",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":616,
                  "y":980},
                "size":{
                  "width":60,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"e272739c112b4cdd8a77628b381e4245",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":154.5,
              "y":968.5},
            "size":{
              "width":85,
              "height":83}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0569b05d7a5146019b9dae753a271ae0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":154.5,
                  "y":968.5},
                "size":{
                  "width":85,
                  "height":83}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u30.png"}},
{
          "id":"4652f4f53aaf4a879f42ae3beb2391a1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":77,
              "y":1071},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8486d420fca14a7c8cd8883c9adc4935",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":77,
                  "y":1071},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"5e84f74c2fb14a74b9e3272d1e4e4791",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":167,
              "y":1071},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"726749a8c8de45b4b70dbe355c4f945d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":167,
                  "y":1071},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"fc2693a56cd14acebc9636e5365438db",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":257,
              "y":1071},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76fd818c0bc5415b91f0af62d545f99b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":257,
                  "y":1071},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"96c0e6684fcf4d6fb66f260438b1ea6d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":347,
              "y":1071},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d624ea24cc946b7bf142576da29e463",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":347,
                  "y":1071},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"fc335ed3eb7a4272a29dc971d65e9805",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":435,
              "y":1071},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22472904d69146d8814c27aa2b27ab3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":435,
                  "y":1071},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"80e75c77dc6a457984c681fb0d35f356",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":525,
              "y":1071},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1317ee92937d4dc4a7d7642632dd8c4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":525,
                  "y":1071},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"f3c19a722200431683043612a1314000",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":615,
              "y":1071},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2ec3c18d5ab40ba943d9417cb9ab13a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":615,
                  "y":1071},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"445c2e4bab39491d8f3948b08b610a4d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":76,
              "y":1161},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1f274e8fc734ea78970fdad2e3a61b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":76,
                  "y":1161},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"75bb7003c56c491d871f9d39f9f646df",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":166,
              "y":1161},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a0c79ae099741a7aa272898844cb099",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":166,
                  "y":1161},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"440b6e549358492985de93eaa711c2ed",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":256,
              "y":1161},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bc6006792c743eb97b80cad1aa4a7b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":256,
                  "y":1161},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"6a25b44de8e949bfafec85c20591edac",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":346,
              "y":1161},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ccf197900834d5d812bc016934c8eb5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":346,
                  "y":1161},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"aa472562abd748038384408476f8959d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":434,
              "y":1161},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d83d75c73ee4383a0f1749ba82c62b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":434,
                  "y":1161},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"b6f3c96854034c69b6072e920669f21e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":524,
              "y":1161},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9867b7f1f9b545ff9bfa2fc1f6311a9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":524,
                  "y":1161},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"4227c75f4c224bd196069abbb2e9a8ca",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":614,
              "y":1161},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c225dedc69284cba82d15ee1fcfca604",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":614,
                  "y":1161},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"3288ad290b8c428eaf015f038776ca44",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":166.5,
              "y":979.5},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b0fcd679f404785b3865159d54c8e5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":166.5,
                  "y":979.5},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u94.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "aee9a39dff414dac92cb6f314479dfec":{
      "scriptId":"u0"},
    "0749b93143744cdfa3d378e277a17b62":{
      "scriptId":"u1"},
    "ce40f3fd2d8a4cc382f14c93d741e731":{
      "scriptId":"u2"},
    "540ad177143a4f689d11e7a27bf0b887":{
      "scriptId":"u3"},
    "ca05e1de32f04f1793cbf90001deed61":{
      "scriptId":"u4"},
    "e327bf63daf94ac9a579d5c42ab98519":{
      "scriptId":"u5"},
    "858abfe2560f4e82b95c29a6841800b6":{
      "scriptId":"u6"},
    "49b7b2a51c354cb48faabf10542eaefe":{
      "scriptId":"u7"},
    "2711342c5180499995a2184dc2b8d754":{
      "scriptId":"u8"},
    "4221d184b638443d9f072ad65f4ce7e5":{
      "scriptId":"u9"},
    "29affc9e389d42c9a2fac89da45c9625":{
      "scriptId":"u10"},
    "1ad79e2cccc44bc68aceb6ad591fb132":{
      "scriptId":"u11"},
    "849f63b671ba4ffba11eebf6845fd8bd":{
      "scriptId":"u12"},
    "08e01afcefff4519ae724d32033aa04f":{
      "scriptId":"u13"},
    "45166b8ad4504279bf47cf403f73d97d":{
      "scriptId":"u14"},
    "ad73b02a9d5b4ee1962c67b2e3a82a72":{
      "scriptId":"u15"},
    "2e5dcdaa59764b658fd19c98c13b64a6":{
      "scriptId":"u16"},
    "e6fff608ad0947ebbdeb09b36af0f8b7":{
      "scriptId":"u17"},
    "3a96670bcffe4daab28ba1a4b6f0ed53":{
      "scriptId":"u18"},
    "fd7724ac30af4b7b91c0ae278fbfc21e":{
      "scriptId":"u19"},
    "8ea408e8cc4a44029af2efc3a22b8b04":{
      "scriptId":"u20"},
    "4729db1aad9c4c6f8f3b483b12408d2c":{
      "scriptId":"u21"},
    "61a828199cb34e779d01d2b49d20da9d":{
      "scriptId":"u22"},
    "8bb89f96edd54a9bbab7e0bc58d4c7df":{
      "scriptId":"u23"},
    "24f9312cab4349e78f6ff2a23e6ffeeb":{
      "scriptId":"u24"},
    "9c2e08d8f183454b84f19bd4a54deec8":{
      "scriptId":"u25"},
    "7f1d82d2e7c74199a181c3869bf6548e":{
      "scriptId":"u26"},
    "ffc25fc19dee4256af8dbe34373cfc4d":{
      "scriptId":"u27"},
    "3dedc03daf794c4c843cc24a2e806ccc":{
      "scriptId":"u28"},
    "67c1ec8679ee4deba30465f089f1c361":{
      "scriptId":"u29"},
    "81249983357943f8b7bee54b3c4b88ce":{
      "scriptId":"u30"},
    "c4ba490c8bab455b92ec957f7d45bf07":{
      "scriptId":"u31"},
    "ab350897e95b4fb3985b1006f7489c1b":{
      "scriptId":"u32"},
    "8a717738154f4cd685c681e0958db3fb":{
      "scriptId":"u33"},
    "22125141d0794e939722241ccb94e489":{
      "scriptId":"u34"},
    "5a5062a87a6547a6b9d51a107c1e3123":{
      "scriptId":"u35"},
    "2ec15006ced541488395e6ef25c8b394":{
      "scriptId":"u36"},
    "2c42aecbf0474bae9940f2d543bc82c3":{
      "scriptId":"u37"},
    "81ac31ba1b2c4102a3f7dce3e6ef4afd":{
      "scriptId":"u38"},
    "3d0a9772bbed4d89ab8f0c8a21cf4f8e":{
      "scriptId":"u39"},
    "bd6a1928713b494cae572a8551acc6df":{
      "scriptId":"u40"},
    "9b2c65ce9b034325bf566db5952be560":{
      "scriptId":"u41"},
    "474dee83150a4dd1b620434c725894fe":{
      "scriptId":"u42"},
    "048b0e481d584a98bdb3027d4d063efe":{
      "scriptId":"u43"},
    "6c307cad7d7648d3b7ed74eedf1118be":{
      "scriptId":"u44"},
    "0e5a56d7de004dfa821460f880ccc543":{
      "scriptId":"u45"},
    "71e6910abf91418ea16de6961eea0e17":{
      "scriptId":"u46"},
    "9c17fe3bf6a84d959401429becf16c24":{
      "scriptId":"u47"},
    "a18e4f89269941388883ce17ac04e271":{
      "scriptId":"u48"},
    "3766313a19d84e5f828bde96fc866573":{
      "scriptId":"u49"},
    "eee7bc4ed9ef4fc4b7132263329739e2":{
      "scriptId":"u50"},
    "ef9c4bd202cd498e969073b379028c50":{
      "scriptId":"u51"},
    "fe68914d24334aa6938b66e24aac4336":{
      "scriptId":"u52"},
    "df740d305a6c460e94553a224da7bdef":{
      "scriptId":"u53"},
    "fb32ee4efbae4e73a855a90998ec9e34":{
      "scriptId":"u54"},
    "f173805154d54efe93a1b3fb42d89e57":{
      "scriptId":"u55"},
    "70208235a7e9460aac3470c7ba6fc358":{
      "scriptId":"u56"},
    "b859f8b471e04e789e778d15d431d667":{
      "scriptId":"u57"},
    "61ff363048714dbda75ffa366f0875e2":{
      "scriptId":"u58"},
    "5d726492821f43c6a55820682838b837":{
      "scriptId":"u59"},
    "700d6eb4a4df4bb4a50cc8e1509b26e0":{
      "scriptId":"u60"},
    "44358ee52ff64461a9a6600a32c8f213":{
      "scriptId":"u61"},
    "65f09164fec44e299a4a4f79e6bf3de4":{
      "scriptId":"u62"},
    "868fe7092f9b42c78d34631c923ae839":{
      "scriptId":"u63"},
    "c498b825263345738ad2e9cbc9d1ecd9":{
      "scriptId":"u64"},
    "ffb4e712e30c45dd807bd2e9c5b50cbf":{
      "scriptId":"u65"},
    "db477eb5a28c4ac78cca01c4e7a9410f":{
      "scriptId":"u66"},
    "e851e9b17188469e85fffc4cf5bd5bcc":{
      "scriptId":"u67"},
    "10c40e9557a74a7bac34a42026565ce3":{
      "scriptId":"u68"},
    "6eb7537c9ff3414895111acb74bd456e":{
      "scriptId":"u69"},
    "82da4490888c4f3f8d7134cc9b71d63e":{
      "scriptId":"u70"},
    "6cfbf233fc5f49b1a7b5ed3d49a65ab4":{
      "scriptId":"u71"},
    "64de5ff41dd94e8f881c1c2d320c3d34":{
      "scriptId":"u72"},
    "8894df23bb884cbda2ee5224aa7203f9":{
      "scriptId":"u73"},
    "312504b78cb141c5a1e101a5dfafcf81":{
      "scriptId":"u74"},
    "d9abd75ed54243a9acac986415605ea4":{
      "scriptId":"u75"},
    "937f6cedb1d643ed949f17ba1b10f227":{
      "scriptId":"u76"},
    "e272739c112b4cdd8a77628b381e4245":{
      "scriptId":"u77"},
    "0569b05d7a5146019b9dae753a271ae0":{
      "scriptId":"u78"},
    "4652f4f53aaf4a879f42ae3beb2391a1":{
      "scriptId":"u79"},
    "8486d420fca14a7c8cd8883c9adc4935":{
      "scriptId":"u80"},
    "5e84f74c2fb14a74b9e3272d1e4e4791":{
      "scriptId":"u81"},
    "726749a8c8de45b4b70dbe355c4f945d":{
      "scriptId":"u82"},
    "fc2693a56cd14acebc9636e5365438db":{
      "scriptId":"u83"},
    "76fd818c0bc5415b91f0af62d545f99b":{
      "scriptId":"u84"},
    "96c0e6684fcf4d6fb66f260438b1ea6d":{
      "scriptId":"u85"},
    "6d624ea24cc946b7bf142576da29e463":{
      "scriptId":"u86"},
    "fc335ed3eb7a4272a29dc971d65e9805":{
      "scriptId":"u87"},
    "22472904d69146d8814c27aa2b27ab3b":{
      "scriptId":"u88"},
    "80e75c77dc6a457984c681fb0d35f356":{
      "scriptId":"u89"},
    "1317ee92937d4dc4a7d7642632dd8c4d":{
      "scriptId":"u90"},
    "f3c19a722200431683043612a1314000":{
      "scriptId":"u91"},
    "f2ec3c18d5ab40ba943d9417cb9ab13a":{
      "scriptId":"u92"},
    "445c2e4bab39491d8f3948b08b610a4d":{
      "scriptId":"u93"},
    "c1f274e8fc734ea78970fdad2e3a61b9":{
      "scriptId":"u94"},
    "75bb7003c56c491d871f9d39f9f646df":{
      "scriptId":"u95"},
    "2a0c79ae099741a7aa272898844cb099":{
      "scriptId":"u96"},
    "440b6e549358492985de93eaa711c2ed":{
      "scriptId":"u97"},
    "7bc6006792c743eb97b80cad1aa4a7b6":{
      "scriptId":"u98"},
    "6a25b44de8e949bfafec85c20591edac":{
      "scriptId":"u99"},
    "6ccf197900834d5d812bc016934c8eb5":{
      "scriptId":"u100"},
    "aa472562abd748038384408476f8959d":{
      "scriptId":"u101"},
    "6d83d75c73ee4383a0f1749ba82c62b8":{
      "scriptId":"u102"},
    "b6f3c96854034c69b6072e920669f21e":{
      "scriptId":"u103"},
    "9867b7f1f9b545ff9bfa2fc1f6311a9f":{
      "scriptId":"u104"},
    "4227c75f4c224bd196069abbb2e9a8ca":{
      "scriptId":"u105"},
    "c225dedc69284cba82d15ee1fcfca604":{
      "scriptId":"u106"},
    "3288ad290b8c428eaf015f038776ca44":{
      "scriptId":"u107"},
    "4b0fcd679f404785b3865159d54c8e5d":{
      "scriptId":"u108"}}});