$axure.loadCurrentPage({
  "url":"loading.html",
  "generationDate":new Date(1491376844869.38),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"opentype"],
  "page":{
    "packageId":"87a835888b6b4ff8b8d20e74757119b4",
    "type":"Axure:Page",
    "name":"loading",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b332d49cc3f14e54bfef36b054e8fe42",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":20,
              "y":35},
            "size":{
              "width":734,
              "height":1295}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab8652e7655d40189568adf4918eb915",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":20,
                  "y":35},
                "size":{
                  "width":734,
                  "height":1295}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u0.png"}},
{
          "id":"31bca3ca73da47ababc64f3e07058716",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":27,
              "y":43},
            "size":{
              "width":720,
              "height":1280}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfc2c7013e0b440bbf6f1b4fa116453b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":27,
                  "y":43},
                "size":{
                  "width":720,
                  "height":1280}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u2.png"}},
{
          "id":"e4340cdd748041df8c0d862f952a569c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00644B},
            "location":{
              "x":27,
              "y":42},
            "size":{
              "width":720,
              "height":1281},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF009999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a63697af8b0f41ab96156bd96daa2dc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00644B},
                "location":{
                  "x":27,
                  "y":42},
                "size":{
                  "width":720,
                  "height":1281},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF009999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/loading/u4.png"}},
{
          "id":"2addc73c6c5047c6a4fe4f7e61d9ff64",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00FF00,
              "opacity":1},
            "location":{
              "x":40,
              "y":60},
            "size":{
              "width":700,
              "height":1250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebc3f89022e14199b40de49058b25493",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00FF00,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":60},
                "size":{
                  "width":700,
                  "height":1250}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 战斗",
                      "target":{
                        "targetType":"page",
                        "url":"战斗.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "b332d49cc3f14e54bfef36b054e8fe42":{
      "scriptId":"u0"},
    "ab8652e7655d40189568adf4918eb915":{
      "scriptId":"u1"},
    "31bca3ca73da47ababc64f3e07058716":{
      "scriptId":"u2"},
    "bfc2c7013e0b440bbf6f1b4fa116453b":{
      "scriptId":"u3"},
    "e4340cdd748041df8c0d862f952a569c":{
      "scriptId":"u4"},
    "a63697af8b0f41ab96156bd96daa2dc0":{
      "scriptId":"u5"},
    "2addc73c6c5047c6a4fe4f7e61d9ff64":{
      "scriptId":"u6"},
    "ebc3f89022e14199b40de49058b25493":{
      "scriptId":"u7"}}});