$axure.loadCurrentPage({
  "url":"技能.html",
  "generationDate":new Date(1477979552172.95),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"cbe1d6ad816340ceae766d0d8c1f32ce",
    "type":"Axure:Page",
    "name":"技能",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"48457416e7b343baa58c167b1bf1b71c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":20,
              "y":25},
            "size":{
              "width":734,
              "height":1295}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c750e31ca57d44738bf6073b7c522a98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":20,
                  "y":25},
                "size":{
                  "width":734,
                  "height":1295}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u0.png"}},
{
          "id":"77714728d6c44a94913070d1b483b648",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":27,
              "y":33},
            "size":{
              "width":720,
              "height":1280}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e63b36bba8040fa8a3e154b3d1a8e38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":27,
                  "y":33},
                "size":{
                  "width":720,
                  "height":1280}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u2.png"}},
{
          "id":"5c0ccc5630cf44e8b8c45b7173cfe83a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":44,
              "y":100},
            "size":{
              "width":680,
              "height":1190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6b9118da4ab483c84a1df99e1f8a3c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":44,
                  "y":100},
                "size":{
                  "width":680,
                  "height":1190}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u4.png"}},
{
          "id":"0dec3bdd90c74960be3b866f9196e9f9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":645,
              "y":42},
            "size":{
              "width":102,
              "height":98}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c84157ffe6f149f5ab3912ad5b67c1bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":645,
                  "y":42},
                "size":{
                  "width":102,
                  "height":98}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主界面",
                      "target":{
                        "targetType":"page",
                        "url":"主界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/副本/u42.png"}},
{
          "id":"a4231a7cbfc242c6914975887b8e1fb7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":232,
              "y":47},
            "size":{
              "width":310,
              "height":93}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77ebe0cadff14bb3b19055f239fe4766",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":232,
                  "y":47},
                "size":{
                  "width":310,
                  "height":93}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"cff234179c0742b796b00327523f24e6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":66,
              "y":150},
            "size":{
              "width":635,
              "height":99}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a99bfcf85bb492ebb1fba7125a6989e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":66,
                  "y":150},
                "size":{
                  "width":635,
                  "height":99}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技能/u10.png"}},
{
          "id":"e5453a71c36146ad9c371b5c326d1b11",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":115,
              "y":171},
            "size":{
              "width":81,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"330e7a3e2a5f4329833bc2dba98e0094",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":115,
                  "y":171},
                "size":{
                  "width":81,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c00bfc90ccf444c7a6533b9b60f0aed6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFF00,
              "opacity":1},
            "location":{
              "x":304,
              "y":171},
            "size":{
              "width":34,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc0e741e59f1402a85480877664e5baa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF00,
                  "opacity":1},
                "location":{
                  "x":304,
                  "y":171},
                "size":{
                  "width":34,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb4978926c1e47b48704b7ae01e59800",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":534,
              "y":164},
            "size":{
              "width":156,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32cff52a26c14862a29368a3b6364102",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":534,
                  "y":164},
                "size":{
                  "width":156,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"32e603e4ac4240b6bbc398ac9a9e2767",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":66,
              "y":259},
            "size":{
              "width":635,
              "height":881}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"997d0217f8f7496ca8c9c3d51bec0ed6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":66,
                  "y":259},
                "size":{
                  "width":635,
                  "height":881}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技能/u18.png"}},
{
          "id":"dcf1c3d37c514939908af87287005843",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":66,
              "y":1155},
            "size":{
              "width":201,
              "height":91}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7af63a8e8c584fa5a2e934502cdb2a9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":66,
                  "y":1155},
                "size":{
                  "width":201,
                  "height":91}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"fc39b97cbcb94045b894dbc02c4d57df",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":283,
              "y":1155},
            "size":{
              "width":201,
              "height":91}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f14d14a0dcb477ca043389606646377",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":283,
                  "y":1155},
                "size":{
                  "width":201,
                  "height":91}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"33c10c8afc144e0fbdf94a3bac1eefa4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":500,
              "y":1155},
            "size":{
              "width":201,
              "height":91}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06e881a3aa2342438baf4ee52b1d704f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":500,
                  "y":1155},
                "size":{
                  "width":201,
                  "height":91}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"a9ce503ace044ee0b6309a3a6d79e79d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":131,
              "y":280},
            "size":{
              "width":160,
              "height":146}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"373cb132310141699da7e00554ce1067",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":131,
                  "y":280},
                "size":{
                  "width":160,
                  "height":146}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技能/u26.png"}},
{
          "id":"fbf45da8dd4142798a7fa3bc581f7f65",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":120,
              "y":409},
            "size":{
              "width":184,
              "height":54}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ac1fc87cbf2483591040bdc2328b70c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":120,
                  "y":409},
                "size":{
                  "width":184,
                  "height":54}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技能/u28.png"}},
{
          "id":"a2dfe58e824a4793a2436d998d2ea55c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":83,
              "y":960},
            "size":{
              "width":587,
              "height":161}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"294031c95d2343c1a34c0d444e7151d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":83,
                  "y":960},
                "size":{
                  "width":587,
                  "height":161}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技能/u30.png"}},
{
          "id":"55e339e2066d4920a3c9e344317a582e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":500,
              "y":1005},
            "size":{
              "width":156,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cffa8a285b1458e90205f637641b461",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":500,
                  "y":1005},
                "size":{
                  "width":156,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"71dc685936384eb48f43d913296176c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":124,
              "y":969},
            "size":{
              "width":116,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4b16d1b0d22424db1849e79c7e00bf4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":124,
                  "y":969},
                "size":{
                  "width":116,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b66bf2ff34b34bafa43fa5af1058ee1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":102,
              "y":1043},
            "size":{
              "width":312,
              "height":68}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbeb7eec51954d5b8951181e9b2fb875",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":102,
                  "y":1043},
                "size":{
                  "width":312,
                  "height":68}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"121a17b240164166898a7dae08b59c78",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":101,
              "y":1024},
            "size":{
              "width":369,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/技能/u38_line.png"}},
{
          "id":"610fda47ad5f4a5c8f73f5b9ec21f66a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":421,
              "y":280},
            "size":{
              "width":160,
              "height":146}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b1c531da17a489296ba3d3ba8dbfec5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":421,
                  "y":280},
                "size":{
                  "width":160,
                  "height":146}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技能/u26.png"}},
{
          "id":"f1afed0396de40af8e1d35a71b9ac7ec",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":410,
              "y":409},
            "size":{
              "width":184,
              "height":54}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd27ce490b1947b6a91256655ed875f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":410,
                  "y":409},
                "size":{
                  "width":184,
                  "height":54}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技能/u28.png"}},
{
          "id":"6bbb17fb1d774098836447e4b09b264e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":131,
              "y":727},
            "size":{
              "width":160,
              "height":146}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51a0ed72d03941f58d2ef3b2a2281fdd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":131,
                  "y":727},
                "size":{
                  "width":160,
                  "height":146}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技能/u26.png"}},
{
          "id":"5442db59323b4a208c58463eb780621c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":120,
              "y":856},
            "size":{
              "width":184,
              "height":54}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"238fb67c9a824c1d97312edf8ed8b168",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":120,
                  "y":856},
                "size":{
                  "width":184,
                  "height":54}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技能/u28.png"}},
{
          "id":"ce9653865371499ca75dbde77dc550e1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":421,
              "y":727},
            "size":{
              "width":160,
              "height":146}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22a7ec1a99ba466b9e6844b0035f7464",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":421,
                  "y":727},
                "size":{
                  "width":160,
                  "height":146}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技能/u26.png"}},
{
          "id":"d8301c032ea44129b5c8e0148221e6b6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":410,
              "y":856},
            "size":{
              "width":184,
              "height":54}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4c1ece9a8884cd58024b27860ea3f57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":410,
                  "y":856},
                "size":{
                  "width":184,
                  "height":54}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技能/u28.png"}},
{
          "id":"6e42419d5f7a4efb842bd1136a26aa59",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":131,
              "y":504},
            "size":{
              "width":160,
              "height":146}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da84791660c6489b84a365fe6dde8cc4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":131,
                  "y":504},
                "size":{
                  "width":160,
                  "height":146}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技能/u26.png"}},
{
          "id":"b42ad060b86e4c138486beff4cf1bc80",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":120,
              "y":633},
            "size":{
              "width":184,
              "height":54}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a397907d2984d959873135e8757781e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":120,
                  "y":633},
                "size":{
                  "width":184,
                  "height":54}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技能/u28.png"}},
{
          "id":"6a26a575c9274ababcf20aa9394378ed",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":421,
              "y":504},
            "size":{
              "width":160,
              "height":146}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01e9a8e56f164c48889a362248e343b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":421,
                  "y":504},
                "size":{
                  "width":160,
                  "height":146}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技能/u26.png"}},
{
          "id":"05649270e6ee4e4c9e37794dbcd2252f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":410,
              "y":633},
            "size":{
              "width":184,
              "height":54}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b0aee7300b544bd981f2a240f42ee04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":410,
                  "y":633},
                "size":{
                  "width":184,
                  "height":54}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技能/u28.png"}},
{
          "id":"48046217eb084943a0ebcb1538d28fcd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":107,
              "y":271},
            "size":{
              "width":200,
              "height":209}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"173d7a7314bf4228aa2c6e729ba697c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":107,
                  "y":271},
                "size":{
                  "width":200,
                  "height":209}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技能/u59.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "48457416e7b343baa58c167b1bf1b71c":{
      "scriptId":"u0"},
    "c750e31ca57d44738bf6073b7c522a98":{
      "scriptId":"u1"},
    "77714728d6c44a94913070d1b483b648":{
      "scriptId":"u2"},
    "1e63b36bba8040fa8a3e154b3d1a8e38":{
      "scriptId":"u3"},
    "5c0ccc5630cf44e8b8c45b7173cfe83a":{
      "scriptId":"u4"},
    "a6b9118da4ab483c84a1df99e1f8a3c1":{
      "scriptId":"u5"},
    "0dec3bdd90c74960be3b866f9196e9f9":{
      "scriptId":"u6"},
    "c84157ffe6f149f5ab3912ad5b67c1bd":{
      "scriptId":"u7"},
    "a4231a7cbfc242c6914975887b8e1fb7":{
      "scriptId":"u8"},
    "77ebe0cadff14bb3b19055f239fe4766":{
      "scriptId":"u9"},
    "cff234179c0742b796b00327523f24e6":{
      "scriptId":"u10"},
    "2a99bfcf85bb492ebb1fba7125a6989e":{
      "scriptId":"u11"},
    "e5453a71c36146ad9c371b5c326d1b11":{
      "scriptId":"u12"},
    "330e7a3e2a5f4329833bc2dba98e0094":{
      "scriptId":"u13"},
    "c00bfc90ccf444c7a6533b9b60f0aed6":{
      "scriptId":"u14"},
    "fc0e741e59f1402a85480877664e5baa":{
      "scriptId":"u15"},
    "eb4978926c1e47b48704b7ae01e59800":{
      "scriptId":"u16"},
    "32cff52a26c14862a29368a3b6364102":{
      "scriptId":"u17"},
    "32e603e4ac4240b6bbc398ac9a9e2767":{
      "scriptId":"u18"},
    "997d0217f8f7496ca8c9c3d51bec0ed6":{
      "scriptId":"u19"},
    "dcf1c3d37c514939908af87287005843":{
      "scriptId":"u20"},
    "7af63a8e8c584fa5a2e934502cdb2a9b":{
      "scriptId":"u21"},
    "fc39b97cbcb94045b894dbc02c4d57df":{
      "scriptId":"u22"},
    "7f14d14a0dcb477ca043389606646377":{
      "scriptId":"u23"},
    "33c10c8afc144e0fbdf94a3bac1eefa4":{
      "scriptId":"u24"},
    "06e881a3aa2342438baf4ee52b1d704f":{
      "scriptId":"u25"},
    "a9ce503ace044ee0b6309a3a6d79e79d":{
      "scriptId":"u26"},
    "373cb132310141699da7e00554ce1067":{
      "scriptId":"u27"},
    "fbf45da8dd4142798a7fa3bc581f7f65":{
      "scriptId":"u28"},
    "5ac1fc87cbf2483591040bdc2328b70c":{
      "scriptId":"u29"},
    "a2dfe58e824a4793a2436d998d2ea55c":{
      "scriptId":"u30"},
    "294031c95d2343c1a34c0d444e7151d6":{
      "scriptId":"u31"},
    "55e339e2066d4920a3c9e344317a582e":{
      "scriptId":"u32"},
    "6cffa8a285b1458e90205f637641b461":{
      "scriptId":"u33"},
    "71dc685936384eb48f43d913296176c2":{
      "scriptId":"u34"},
    "b4b16d1b0d22424db1849e79c7e00bf4":{
      "scriptId":"u35"},
    "b66bf2ff34b34bafa43fa5af1058ee1e":{
      "scriptId":"u36"},
    "fbeb7eec51954d5b8951181e9b2fb875":{
      "scriptId":"u37"},
    "121a17b240164166898a7dae08b59c78":{
      "scriptId":"u38"},
    "610fda47ad5f4a5c8f73f5b9ec21f66a":{
      "scriptId":"u39"},
    "5b1c531da17a489296ba3d3ba8dbfec5":{
      "scriptId":"u40"},
    "f1afed0396de40af8e1d35a71b9ac7ec":{
      "scriptId":"u41"},
    "bd27ce490b1947b6a91256655ed875f0":{
      "scriptId":"u42"},
    "6bbb17fb1d774098836447e4b09b264e":{
      "scriptId":"u43"},
    "51a0ed72d03941f58d2ef3b2a2281fdd":{
      "scriptId":"u44"},
    "5442db59323b4a208c58463eb780621c":{
      "scriptId":"u45"},
    "238fb67c9a824c1d97312edf8ed8b168":{
      "scriptId":"u46"},
    "ce9653865371499ca75dbde77dc550e1":{
      "scriptId":"u47"},
    "22a7ec1a99ba466b9e6844b0035f7464":{
      "scriptId":"u48"},
    "d8301c032ea44129b5c8e0148221e6b6":{
      "scriptId":"u49"},
    "a4c1ece9a8884cd58024b27860ea3f57":{
      "scriptId":"u50"},
    "6e42419d5f7a4efb842bd1136a26aa59":{
      "scriptId":"u51"},
    "da84791660c6489b84a365fe6dde8cc4":{
      "scriptId":"u52"},
    "b42ad060b86e4c138486beff4cf1bc80":{
      "scriptId":"u53"},
    "6a397907d2984d959873135e8757781e":{
      "scriptId":"u54"},
    "6a26a575c9274ababcf20aa9394378ed":{
      "scriptId":"u55"},
    "01e9a8e56f164c48889a362248e343b5":{
      "scriptId":"u56"},
    "05649270e6ee4e4c9e37794dbcd2252f":{
      "scriptId":"u57"},
    "5b0aee7300b544bd981f2a240f42ee04":{
      "scriptId":"u58"},
    "48046217eb084943a0ebcb1538d28fcd":{
      "scriptId":"u59"},
    "173d7a7314bf4228aa2c6e729ba697c0":{
      "scriptId":"u60"}}});