$axure.loadCurrentPage({
  "url":"商店.html",
  "generationDate":new Date(1477979555800.11),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"432f98b04a2246db89d801eb9d405bbc",
    "type":"Axure:Page",
    "name":"商店",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9794568d1ec5429e8aef50430a8c375b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":20,
              "y":35},
            "size":{
              "width":734,
              "height":1295}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b624448793144e96a37e01f3cce39b0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":20,
                  "y":35},
                "size":{
                  "width":734,
                  "height":1295}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u0.png"}},
{
          "id":"9f11713060984e6a9b9ad9f240a2a6c6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":27,
              "y":43},
            "size":{
              "width":720,
              "height":1280}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3592edfb7f0406e9ce6715aac7abacc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":27,
                  "y":43},
                "size":{
                  "width":720,
                  "height":1280}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u2.png"}},
{
          "id":"b6caf2aad8894e60801d54aa9a7e6a88",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":44,
              "y":105},
            "size":{
              "width":680,
              "height":1190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7fb6a5dd8ab43e892e78f1fc056871e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":44,
                  "y":105},
                "size":{
                  "width":680,
                  "height":1190}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u4.png"}},
{
          "id":"096946bad93e489ba9bea6ac56be2fd5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":645,
              "y":47},
            "size":{
              "width":102,
              "height":98}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7bcfeaff43e42d3a3891f6e4cd1596b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":645,
                  "y":47},
                "size":{
                  "width":102,
                  "height":98}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主界面",
                      "target":{
                        "targetType":"page",
                        "url":"主界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/副本/u42.png"}},
{
          "id":"f9835005017141ed888ffe47452a2113",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":64,
              "y":1130},
            "size":{
              "width":636,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/付费/u18_line.png"}},
{
          "id":"51ecb90dc8ff4d789a597cfc12ceca30",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":68,
              "y":884},
            "size":{
              "width":635,
              "height":385}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f2614d09f9a4754b69c0df1c90e5b8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":68,
                  "y":884},
                "size":{
                  "width":635,
                  "height":385}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u10.png"}},
{
          "id":"2c0d05533e82403ebd885a3f0bb43b84",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":77,
              "y":895},
            "size":{
              "width":77,
              "height":58}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef0dec98c9d64841b7efc83f5aeba15f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":77,
                  "y":895},
                "size":{
                  "width":77,
                  "height":58}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"d52d37df747342308a0ff7aab1cf4acc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":164,
              "y":895},
            "size":{
              "width":77,
              "height":58}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"caf8f4d9e8934893a13ad26b41a42e0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":164,
                  "y":895},
                "size":{
                  "width":77,
                  "height":58}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"9128115694e54701923f79c1b59e7a88",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":251,
              "y":895},
            "size":{
              "width":77,
              "height":58}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6da71cdba98a45acac8657e9cb84aa95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":251,
                  "y":895},
                "size":{
                  "width":77,
                  "height":58}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"437b2e2e6a4543afa55c2bdf14320578",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":338,
              "y":895},
            "size":{
              "width":77,
              "height":58}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"488940bfd6bc45bd82c4f333b223e0a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":338,
                  "y":895},
                "size":{
                  "width":77,
                  "height":58}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"dfa0f4d0cb824959a91663e9c6de9c96",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":425,
              "y":895},
            "size":{
              "width":77,
              "height":58}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2a04a4737c54467a913cce3e51658dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":425,
                  "y":895},
                "size":{
                  "width":77,
                  "height":58}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"617594fd3ba84fd8ac0a1c9489522ab7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":92,
              "y":900},
            "size":{
              "width":49,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb725f28e51145cca0ac528f6325feb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":92,
                  "y":900},
                "size":{
                  "width":49,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u108.png"}},
{
          "id":"c0810562940942bca92f2e28043503e0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":69,
              "y":155},
            "size":{
              "width":635,
              "height":689}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"547083c56ffa47a79e00da54b2af28cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":69,
                  "y":155},
                "size":{
                  "width":635,
                  "height":689}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u12.png"}},
{
          "id":"89a1116dd90f4c83b4d6036a34bba45e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":92,
              "y":180},
            "size":{
              "width":176,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6dc6385e9974a1e9376e1e6aa3282f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":92,
                  "y":180},
                "size":{
                  "width":176,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"2d96375ccc724c1f921c094e7bd4bd89",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":308,
              "y":180},
            "size":{
              "width":176,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1dc93741373a416aa4069b55a4cda2c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":308,
                  "y":180},
                "size":{
                  "width":176,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"8d2ae953310d4958a6af8de9774f8696",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":519,
              "y":180},
            "size":{
              "width":176,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f219a0e8dc0f4a0e8903028865deffa9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":519,
                  "y":180},
                "size":{
                  "width":176,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"e4399edf0f1f4b59bcdf5a2d6f245e07",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":77,
              "y":297},
            "size":{
              "width":317,
              "height":528}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ccd62da880949aab846eacb30ec5e00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":77,
                  "y":297},
                "size":{
                  "width":317,
                  "height":528}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商店/u31.png"}},
{
          "id":"cb8f4e9ce1c242b3a83b50576befc012",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":83,
              "y":763},
            "size":{
              "width":106,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f3cac1169224493a43fbe52052d7917",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":83,
                  "y":763},
                "size":{
                  "width":106,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"af7136b6bd6a4a719f905b97fa33a9ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":199,
              "y":779},
            "size":{
              "width":245,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a7dc1f8a4e84dcfbf90340c59f91472",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":199,
                  "y":779},
                "size":{
                  "width":245,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7cc65ca6c4be43cba1d5bcd9736db810",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":83,
              "y":743},
            "size":{
              "width":287,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商店/u37_line.png"}},
{
          "id":"aecb569d7f3e46f19763294a39414066",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":77,
              "y":980},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a883db9dee1431fa40287bafd355aca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":77,
                  "y":980},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"ddd27c39f6ff4db5849d381bec13f37e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":167,
              "y":980},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67528d6c423a4f0a8347dcec9d2154fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":167,
                  "y":980},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"d7d2dc05b9234cb1b0066f7f412fdf44",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":257,
              "y":980},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51cb1a97d6fb45ff846653c695c0951f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":257,
                  "y":980},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"80599e5a7d97496c8557a78af965b1d9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":347,
              "y":980},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3766b73ecd274203aeb3bdfdc6514f39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":347,
                  "y":980},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"17195949dbf54440ba07bced1bfd1477",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":436,
              "y":980},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3d4de4fd7f84fb5918567b63dd54f58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":436,
                  "y":980},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"d6c8d34ef3764369953a84b4a1c26fc8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":526,
              "y":980},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c23768da7ea44d896def9ac8541ad91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":526,
                  "y":980},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"e2f58c4173714393a8004fa9c83da0ea",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":616,
              "y":980},
            "size":{
              "width":60,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF66FF00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ab03174bdb8417e935d0aa447314996",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":616,
                  "y":980},
                "size":{
                  "width":60,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"a504261f606b497ba1cc27da6223c6b3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":154.5,
              "y":968.5},
            "size":{
              "width":85,
              "height":83}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"490e2338510a47ffa49f8702370b3a93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":154.5,
                  "y":968.5},
                "size":{
                  "width":85,
                  "height":83}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u30.png"}},
{
          "id":"69fe84dc2b704ebfb44498fffdba7673",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":77,
              "y":1071},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79c76ceb386647e19668354d061f96c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":77,
                  "y":1071},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"5accc1be3847482e824c92690bea95b8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":167,
              "y":1071},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5cdfa30d4064f2892160b2976ce446d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":167,
                  "y":1071},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"4299ed24d6134865a71eb5e740daa271",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":257,
              "y":1071},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87c10af8f05f43f3820682cac14a852c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":257,
                  "y":1071},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"a73c7aa642944a5b8432d671d10cfaa7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":347,
              "y":1071},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab63ada898b4481c95f1d00b65642f3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":347,
                  "y":1071},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"3562f46aa0e241799a1ddbb7e6c649d0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":435,
              "y":1071},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a4a8b804e5c4109929f808f983dc4d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":435,
                  "y":1071},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"543bf57d494c485a8988ff2a2372a939",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":525,
              "y":1071},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd45840a9b934a3586cdd21100b9bbc2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":525,
                  "y":1071},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"6d4e228529d84aa79e33489cc167f182",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":615,
              "y":1071},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4975bfd2a2f4564996a5f4c278277b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":615,
                  "y":1071},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"c2c6ab511de8451f89de5668ae0e4ec4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":76,
              "y":1161},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3a86585e3bf4baea50cc8d25690da44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":76,
                  "y":1161},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"c1b0ad7340f442449ee49392361b2f88",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":166,
              "y":1161},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d031795552340b9be94af7d80b89df6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":166,
                  "y":1161},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"f39d544af62f4836a9d68ca6a869aee1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":256,
              "y":1161},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b5c86c0e79a434fa6816bef9847ca42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":256,
                  "y":1161},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"b7217ece3fac45b9bb29bdc010e351ee",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":346,
              "y":1161},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57977f078858493bb40b52085619b24c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":346,
                  "y":1161},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"bbab81291080492891a21dfb9a706eec",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":434,
              "y":1161},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7651b6104fa401195b453dfabf80372",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":434,
                  "y":1161},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"34ac04ae519e4d27bdbb67de3b808ae4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":524,
              "y":1161},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07ed00e5e4f843e7b92fa6af308b30e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":524,
                  "y":1161},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"9c03b1302d2e4076a0430d157f64af95",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":614,
              "y":1161},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2eae7b784ed54fc28f508d6631978cdf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":614,
                  "y":1161},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"af186955f50a43778e37a7c6c568853e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":166.5,
              "y":979.5},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4ae5ac81a734d33ae4f0f72308afebd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":166.5,
                  "y":979.5},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u94.png"}},
{
          "id":"0afbe8cd00c44b1f8cbc32caf82989f3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":404,
              "y":382},
            "size":{
              "width":291,
              "height":443}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc3f65bced264d90b9bcf6dbf5bee14e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":404,
                  "y":382},
                "size":{
                  "width":291,
                  "height":443}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u72.png"}},
{
          "id":"099bd325897d4200b106bfb5dd65f739",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.25",
            "location":{
              "x":421,
              "y":392},
            "size":{
              "width":250,
              "height":43},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF66FF00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f17cc26e03c34cccb8fd1d6fd2f240a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.25",
                "location":{
                  "x":421,
                  "y":392},
                "size":{
                  "width":250,
                  "height":43},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u90.png"}},
{
          "id":"bb8ac52130934c1b9faa53783b768371",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":509,
              "y":402},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f8e9e578a0541a3823907cb38cfee64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":509,
                  "y":402},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08b03d0928c947f198717a88a3dd41e7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":421,
              "y":442},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93efe450c72944b2a6d9215c4e3a5984",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":421,
                  "y":442},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"fc9e830d52f042dbadbb901971e85e26",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":421,
              "y":442},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ef2f39c5656456fba1d7698ff30feee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":421,
                  "y":442},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u94.png"}},
{
          "id":"43e0f2f2c38f4b798279acb92fe19b1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":503,
              "y":444},
            "size":{
              "width":146,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b30097bb3ab45278de50775eb0b662a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":503,
                  "y":444},
                "size":{
                  "width":146,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"29ba2db2642f40c4a7c1ac639f591448",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":503,
              "y":478},
            "size":{
              "width":126,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"698d7dc78a274c1a8e089102bb553d68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":503,
                  "y":478},
                "size":{
                  "width":126,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c680517d7df34f4ba2e537a3b2af6216",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCFF00,
              "opacity":1},
            "location":{
              "x":421,
              "y":626},
            "size":{
              "width":287,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcb268d02fb5433589eb1cb087232ca6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCFF00,
                  "opacity":1},
                "location":{
                  "x":421,
                  "y":626},
                "size":{
                  "width":287,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d3405511c7f414e9c72a0d06778287b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CC00,
              "opacity":1},
            "location":{
              "x":421,
              "y":660},
            "size":{
              "width":202,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5551f3209de745e0a1a6467c02bbe2c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CC00,
                  "opacity":1},
                "location":{
                  "x":421,
                  "y":660},
                "size":{
                  "width":202,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"11978399407e4bee9401a85e8d66c4b0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":570,
              "y":766},
            "size":{
              "width":111,
              "height":58}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e7718e1da884d1790416d6fbb2130a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":570,
                  "y":766},
                "size":{
                  "width":111,
                  "height":58}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}},
{
          "id":"ac9e2ec07f9447eea2b7a5b495d97ca1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF00CC,
              "opacity":1},
            "location":{
              "x":421,
              "y":536},
            "size":{
              "width":202,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f028ebf2c664b42a20c3f8b9f24094f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF00CC,
                  "opacity":1},
                "location":{
                  "x":421,
                  "y":536},
                "size":{
                  "width":202,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"27a45304c0794f60b206027d9938b363",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":648,
              "y":386},
            "size":{
              "width":47,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a15c7f13388b4711a8fa081f5f3cd03c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":648,
                  "y":386},
                "size":{
                  "width":47,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u216.png"}},
{
          "id":"5f0fbce23dd1474c8b40f33ca557c7d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCFF00,
              "opacity":1},
            "location":{
              "x":421,
              "y":508},
            "size":{
              "width":270,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d2be2894b4e4bd8bd909e1515b59ed3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCFF00,
                  "opacity":1},
                "location":{
                  "x":421,
                  "y":508},
                "size":{
                  "width":270,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ea0b86ddc244c4cb0671c95f3c75d1a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":408,
              "y":769},
            "size":{
              "width":152,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0742a584c5f4014a5f954c59a97900c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":408,
                  "y":769},
                "size":{
                  "width":152,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商店/u110.png"}},
{
          "id":"afcfe47ddb7945c48124ab31bf593971",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":421,
              "y":779},
            "size":{
              "width":34,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"782e79bb220e41729e1bdee7e994e09b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":421,
                  "y":779},
                "size":{
                  "width":34,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u22.png"}},
{
          "id":"8b5b7cd811964664ac2e528c809191c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":442,
              "y":783},
            "size":{
              "width":118,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d9d5bf6d46d4bf5a71b547dd85fa92f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":442,
                  "y":783},
                "size":{
                  "width":118,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d6de60a3bea44301b4b786a7ea12de5f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":96.5,
              "y":324},
            "size":{
              "width":278,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2df0374db4b84904a9199b09d4d23fd4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":96.5,
                  "y":324},
                "size":{
                  "width":278,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商店/u116.png"}},
{
          "id":"c063a9ee70a348749aba8e867d122d53",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":110.5,
              "y":336},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"906f48efa9d24185995194f4a6a6eb9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":110.5,
                  "y":336},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"582ee9632b2345e383e762e267de70ce",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":186.5,
              "y":374},
            "size":{
              "width":26,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"839fddb7dd6f44b0995d369ed08d9d31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":186.5,
                  "y":374},
                "size":{
                  "width":26,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u22.png"}},
{
          "id":"2ca13fd215df4fcd841514480f0675b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":209.5,
              "y":376},
            "size":{
              "width":63,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0872ba5a9c74bba9bf79c57a76a509c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":209.5,
                  "y":376},
                "size":{
                  "width":63,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"97d02923d1c0416cb69be43f9cce43d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":193,
              "y":336},
            "size":{
              "width":148,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4490f9995b56408081e98558a2a99d46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":193,
                  "y":336},
                "size":{
                  "width":148,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e0248e922c246fb80a7eaa34d66d541",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":96,
              "y":421},
            "size":{
              "width":278,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9402f1ec43b43848cb614665fa16d5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":96,
                  "y":421},
                "size":{
                  "width":278,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商店/u116.png"}},
{
          "id":"d70d471101034c2d9624cf0e6e894ea2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":110,
              "y":433},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70f0197189f448cd81dad896e40cea7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":110,
                  "y":433},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"40521fe81a23456780d08d8fbdbab53f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":186,
              "y":471},
            "size":{
              "width":26,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf9b760aefcc447f8456a1abec6ea201",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":186,
                  "y":471},
                "size":{
                  "width":26,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u22.png"}},
{
          "id":"b6d80dc054144aad80d3e0e4df3ab175",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":210,
              "y":473},
            "size":{
              "width":63,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31cdbaf1cbed4f00a43114602fe2e120",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":210,
                  "y":473},
                "size":{
                  "width":63,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d8289dd478f4b7181dd61215d90c992",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":193,
              "y":433},
            "size":{
              "width":148,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"549ef39dcf5f477bb6922c29755db396",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":193,
                  "y":433},
                "size":{
                  "width":148,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"adb5219fd5894b7a87e1d223b0dceef5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":97,
              "y":521},
            "size":{
              "width":278,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9427a85ed5e4c1788b8bb92d460c6d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":97,
                  "y":521},
                "size":{
                  "width":278,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商店/u116.png"}},
{
          "id":"939bf8b06acf402c914be1e03d217d3f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":111,
              "y":533},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbf5158305044af2a06e0c6e99e336b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":111,
                  "y":533},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"d0ac2736f70c46569967c4403740c929",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":187,
              "y":571},
            "size":{
              "width":26,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da075e83251040ce93146de7980cb03a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":187,
                  "y":571},
                "size":{
                  "width":26,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u22.png"}},
{
          "id":"374b0a5a2e7c4ffdacf9e0df9c3584fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":211,
              "y":573},
            "size":{
              "width":63,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3174147441904fd39b809ee786336d5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":211,
                  "y":573},
                "size":{
                  "width":63,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d3f37373593d4b35ae35d9a41ff038a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":194,
              "y":533},
            "size":{
              "width":148,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a75243cbeeb94a3bbd45ccfa4ed8e8f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":194,
                  "y":533},
                "size":{
                  "width":148,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b2e2330768444664afcaadbe9f1c1093",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":96,
              "y":629},
            "size":{
              "width":278,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec9d62ee2bf541018c00c06a899f497f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":96,
                  "y":629},
                "size":{
                  "width":278,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商店/u116.png"}},
{
          "id":"ed673a4a559e4786b4d856c7feac49ec",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.5",
            "location":{
              "x":110,
              "y":641},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42d8b8c4fcdd4ccca838b3d37d1b9444",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.5",
                "location":{
                  "x":110,
                  "y":641},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/背包/u16.png"}},
{
          "id":"ff11073c9c2b458c8eb091049af77795",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":186,
              "y":679},
            "size":{
              "width":26,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"656dcab133e244268b3e62407df936ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":186,
                  "y":679},
                "size":{
                  "width":26,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u22.png"}},
{
          "id":"737ec7b9996649aebef89c4db9bb248a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":210,
              "y":681},
            "size":{
              "width":63,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10d808af721543fcb32f7371bbe55539",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":210,
                  "y":681},
                "size":{
                  "width":63,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"713a3594cc5c4d26b3721375b9eac9c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":193,
              "y":641},
            "size":{
              "width":148,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd64f8443cf04e54bfd76570fc8ac40c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":193,
                  "y":641},
                "size":{
                  "width":148,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "9794568d1ec5429e8aef50430a8c375b":{
      "scriptId":"u0"},
    "b624448793144e96a37e01f3cce39b0e":{
      "scriptId":"u1"},
    "9f11713060984e6a9b9ad9f240a2a6c6":{
      "scriptId":"u2"},
    "f3592edfb7f0406e9ce6715aac7abacc":{
      "scriptId":"u3"},
    "b6caf2aad8894e60801d54aa9a7e6a88":{
      "scriptId":"u4"},
    "b7fb6a5dd8ab43e892e78f1fc056871e":{
      "scriptId":"u5"},
    "096946bad93e489ba9bea6ac56be2fd5":{
      "scriptId":"u6"},
    "a7bcfeaff43e42d3a3891f6e4cd1596b":{
      "scriptId":"u7"},
    "f9835005017141ed888ffe47452a2113":{
      "scriptId":"u8"},
    "51ecb90dc8ff4d789a597cfc12ceca30":{
      "scriptId":"u9"},
    "7f2614d09f9a4754b69c0df1c90e5b8f":{
      "scriptId":"u10"},
    "2c0d05533e82403ebd885a3f0bb43b84":{
      "scriptId":"u11"},
    "ef0dec98c9d64841b7efc83f5aeba15f":{
      "scriptId":"u12"},
    "d52d37df747342308a0ff7aab1cf4acc":{
      "scriptId":"u13"},
    "caf8f4d9e8934893a13ad26b41a42e0e":{
      "scriptId":"u14"},
    "9128115694e54701923f79c1b59e7a88":{
      "scriptId":"u15"},
    "6da71cdba98a45acac8657e9cb84aa95":{
      "scriptId":"u16"},
    "437b2e2e6a4543afa55c2bdf14320578":{
      "scriptId":"u17"},
    "488940bfd6bc45bd82c4f333b223e0a7":{
      "scriptId":"u18"},
    "dfa0f4d0cb824959a91663e9c6de9c96":{
      "scriptId":"u19"},
    "b2a04a4737c54467a913cce3e51658dc":{
      "scriptId":"u20"},
    "617594fd3ba84fd8ac0a1c9489522ab7":{
      "scriptId":"u21"},
    "cb725f28e51145cca0ac528f6325feb4":{
      "scriptId":"u22"},
    "c0810562940942bca92f2e28043503e0":{
      "scriptId":"u23"},
    "547083c56ffa47a79e00da54b2af28cb":{
      "scriptId":"u24"},
    "89a1116dd90f4c83b4d6036a34bba45e":{
      "scriptId":"u25"},
    "c6dc6385e9974a1e9376e1e6aa3282f6":{
      "scriptId":"u26"},
    "2d96375ccc724c1f921c094e7bd4bd89":{
      "scriptId":"u27"},
    "1dc93741373a416aa4069b55a4cda2c5":{
      "scriptId":"u28"},
    "8d2ae953310d4958a6af8de9774f8696":{
      "scriptId":"u29"},
    "f219a0e8dc0f4a0e8903028865deffa9":{
      "scriptId":"u30"},
    "e4399edf0f1f4b59bcdf5a2d6f245e07":{
      "scriptId":"u31"},
    "1ccd62da880949aab846eacb30ec5e00":{
      "scriptId":"u32"},
    "cb8f4e9ce1c242b3a83b50576befc012":{
      "scriptId":"u33"},
    "4f3cac1169224493a43fbe52052d7917":{
      "scriptId":"u34"},
    "af7136b6bd6a4a719f905b97fa33a9ec":{
      "scriptId":"u35"},
    "8a7dc1f8a4e84dcfbf90340c59f91472":{
      "scriptId":"u36"},
    "7cc65ca6c4be43cba1d5bcd9736db810":{
      "scriptId":"u37"},
    "aecb569d7f3e46f19763294a39414066":{
      "scriptId":"u38"},
    "6a883db9dee1431fa40287bafd355aca":{
      "scriptId":"u39"},
    "ddd27c39f6ff4db5849d381bec13f37e":{
      "scriptId":"u40"},
    "67528d6c423a4f0a8347dcec9d2154fd":{
      "scriptId":"u41"},
    "d7d2dc05b9234cb1b0066f7f412fdf44":{
      "scriptId":"u42"},
    "51cb1a97d6fb45ff846653c695c0951f":{
      "scriptId":"u43"},
    "80599e5a7d97496c8557a78af965b1d9":{
      "scriptId":"u44"},
    "3766b73ecd274203aeb3bdfdc6514f39":{
      "scriptId":"u45"},
    "17195949dbf54440ba07bced1bfd1477":{
      "scriptId":"u46"},
    "c3d4de4fd7f84fb5918567b63dd54f58":{
      "scriptId":"u47"},
    "d6c8d34ef3764369953a84b4a1c26fc8":{
      "scriptId":"u48"},
    "2c23768da7ea44d896def9ac8541ad91":{
      "scriptId":"u49"},
    "e2f58c4173714393a8004fa9c83da0ea":{
      "scriptId":"u50"},
    "7ab03174bdb8417e935d0aa447314996":{
      "scriptId":"u51"},
    "a504261f606b497ba1cc27da6223c6b3":{
      "scriptId":"u52"},
    "490e2338510a47ffa49f8702370b3a93":{
      "scriptId":"u53"},
    "69fe84dc2b704ebfb44498fffdba7673":{
      "scriptId":"u54"},
    "79c76ceb386647e19668354d061f96c3":{
      "scriptId":"u55"},
    "5accc1be3847482e824c92690bea95b8":{
      "scriptId":"u56"},
    "b5cdfa30d4064f2892160b2976ce446d":{
      "scriptId":"u57"},
    "4299ed24d6134865a71eb5e740daa271":{
      "scriptId":"u58"},
    "87c10af8f05f43f3820682cac14a852c":{
      "scriptId":"u59"},
    "a73c7aa642944a5b8432d671d10cfaa7":{
      "scriptId":"u60"},
    "ab63ada898b4481c95f1d00b65642f3c":{
      "scriptId":"u61"},
    "3562f46aa0e241799a1ddbb7e6c649d0":{
      "scriptId":"u62"},
    "7a4a8b804e5c4109929f808f983dc4d3":{
      "scriptId":"u63"},
    "543bf57d494c485a8988ff2a2372a939":{
      "scriptId":"u64"},
    "bd45840a9b934a3586cdd21100b9bbc2":{
      "scriptId":"u65"},
    "6d4e228529d84aa79e33489cc167f182":{
      "scriptId":"u66"},
    "a4975bfd2a2f4564996a5f4c278277b7":{
      "scriptId":"u67"},
    "c2c6ab511de8451f89de5668ae0e4ec4":{
      "scriptId":"u68"},
    "e3a86585e3bf4baea50cc8d25690da44":{
      "scriptId":"u69"},
    "c1b0ad7340f442449ee49392361b2f88":{
      "scriptId":"u70"},
    "8d031795552340b9be94af7d80b89df6":{
      "scriptId":"u71"},
    "f39d544af62f4836a9d68ca6a869aee1":{
      "scriptId":"u72"},
    "4b5c86c0e79a434fa6816bef9847ca42":{
      "scriptId":"u73"},
    "b7217ece3fac45b9bb29bdc010e351ee":{
      "scriptId":"u74"},
    "57977f078858493bb40b52085619b24c":{
      "scriptId":"u75"},
    "bbab81291080492891a21dfb9a706eec":{
      "scriptId":"u76"},
    "e7651b6104fa401195b453dfabf80372":{
      "scriptId":"u77"},
    "34ac04ae519e4d27bdbb67de3b808ae4":{
      "scriptId":"u78"},
    "07ed00e5e4f843e7b92fa6af308b30e0":{
      "scriptId":"u79"},
    "9c03b1302d2e4076a0430d157f64af95":{
      "scriptId":"u80"},
    "2eae7b784ed54fc28f508d6631978cdf":{
      "scriptId":"u81"},
    "af186955f50a43778e37a7c6c568853e":{
      "scriptId":"u82"},
    "b4ae5ac81a734d33ae4f0f72308afebd":{
      "scriptId":"u83"},
    "0afbe8cd00c44b1f8cbc32caf82989f3":{
      "scriptId":"u84"},
    "fc3f65bced264d90b9bcf6dbf5bee14e":{
      "scriptId":"u85"},
    "099bd325897d4200b106bfb5dd65f739":{
      "scriptId":"u86"},
    "f17cc26e03c34cccb8fd1d6fd2f240a7":{
      "scriptId":"u87"},
    "bb8ac52130934c1b9faa53783b768371":{
      "scriptId":"u88"},
    "5f8e9e578a0541a3823907cb38cfee64":{
      "scriptId":"u89"},
    "08b03d0928c947f198717a88a3dd41e7":{
      "scriptId":"u90"},
    "93efe450c72944b2a6d9215c4e3a5984":{
      "scriptId":"u91"},
    "fc9e830d52f042dbadbb901971e85e26":{
      "scriptId":"u92"},
    "3ef2f39c5656456fba1d7698ff30feee":{
      "scriptId":"u93"},
    "43e0f2f2c38f4b798279acb92fe19b1f":{
      "scriptId":"u94"},
    "1b30097bb3ab45278de50775eb0b662a":{
      "scriptId":"u95"},
    "29ba2db2642f40c4a7c1ac639f591448":{
      "scriptId":"u96"},
    "698d7dc78a274c1a8e089102bb553d68":{
      "scriptId":"u97"},
    "c680517d7df34f4ba2e537a3b2af6216":{
      "scriptId":"u98"},
    "fcb268d02fb5433589eb1cb087232ca6":{
      "scriptId":"u99"},
    "8d3405511c7f414e9c72a0d06778287b":{
      "scriptId":"u100"},
    "5551f3209de745e0a1a6467c02bbe2c5":{
      "scriptId":"u101"},
    "11978399407e4bee9401a85e8d66c4b0":{
      "scriptId":"u102"},
    "1e7718e1da884d1790416d6fbb2130a3":{
      "scriptId":"u103"},
    "ac9e2ec07f9447eea2b7a5b495d97ca1":{
      "scriptId":"u104"},
    "3f028ebf2c664b42a20c3f8b9f24094f":{
      "scriptId":"u105"},
    "27a45304c0794f60b206027d9938b363":{
      "scriptId":"u106"},
    "a15c7f13388b4711a8fa081f5f3cd03c":{
      "scriptId":"u107"},
    "5f0fbce23dd1474c8b40f33ca557c7d9":{
      "scriptId":"u108"},
    "8d2be2894b4e4bd8bd909e1515b59ed3":{
      "scriptId":"u109"},
    "2ea0b86ddc244c4cb0671c95f3c75d1a":{
      "scriptId":"u110"},
    "f0742a584c5f4014a5f954c59a97900c":{
      "scriptId":"u111"},
    "afcfe47ddb7945c48124ab31bf593971":{
      "scriptId":"u112"},
    "782e79bb220e41729e1bdee7e994e09b":{
      "scriptId":"u113"},
    "8b5b7cd811964664ac2e528c809191c3":{
      "scriptId":"u114"},
    "5d9d5bf6d46d4bf5a71b547dd85fa92f":{
      "scriptId":"u115"},
    "d6de60a3bea44301b4b786a7ea12de5f":{
      "scriptId":"u116"},
    "2df0374db4b84904a9199b09d4d23fd4":{
      "scriptId":"u117"},
    "c063a9ee70a348749aba8e867d122d53":{
      "scriptId":"u118"},
    "906f48efa9d24185995194f4a6a6eb9b":{
      "scriptId":"u119"},
    "582ee9632b2345e383e762e267de70ce":{
      "scriptId":"u120"},
    "839fddb7dd6f44b0995d369ed08d9d31":{
      "scriptId":"u121"},
    "2ca13fd215df4fcd841514480f0675b0":{
      "scriptId":"u122"},
    "d0872ba5a9c74bba9bf79c57a76a509c":{
      "scriptId":"u123"},
    "97d02923d1c0416cb69be43f9cce43d8":{
      "scriptId":"u124"},
    "4490f9995b56408081e98558a2a99d46":{
      "scriptId":"u125"},
    "0e0248e922c246fb80a7eaa34d66d541":{
      "scriptId":"u126"},
    "b9402f1ec43b43848cb614665fa16d5d":{
      "scriptId":"u127"},
    "d70d471101034c2d9624cf0e6e894ea2":{
      "scriptId":"u128"},
    "70f0197189f448cd81dad896e40cea7f":{
      "scriptId":"u129"},
    "40521fe81a23456780d08d8fbdbab53f":{
      "scriptId":"u130"},
    "bf9b760aefcc447f8456a1abec6ea201":{
      "scriptId":"u131"},
    "b6d80dc054144aad80d3e0e4df3ab175":{
      "scriptId":"u132"},
    "31cdbaf1cbed4f00a43114602fe2e120":{
      "scriptId":"u133"},
    "5d8289dd478f4b7181dd61215d90c992":{
      "scriptId":"u134"},
    "549ef39dcf5f477bb6922c29755db396":{
      "scriptId":"u135"},
    "adb5219fd5894b7a87e1d223b0dceef5":{
      "scriptId":"u136"},
    "c9427a85ed5e4c1788b8bb92d460c6d9":{
      "scriptId":"u137"},
    "939bf8b06acf402c914be1e03d217d3f":{
      "scriptId":"u138"},
    "bbf5158305044af2a06e0c6e99e336b9":{
      "scriptId":"u139"},
    "d0ac2736f70c46569967c4403740c929":{
      "scriptId":"u140"},
    "da075e83251040ce93146de7980cb03a":{
      "scriptId":"u141"},
    "374b0a5a2e7c4ffdacf9e0df9c3584fd":{
      "scriptId":"u142"},
    "3174147441904fd39b809ee786336d5b":{
      "scriptId":"u143"},
    "d3f37373593d4b35ae35d9a41ff038a2":{
      "scriptId":"u144"},
    "a75243cbeeb94a3bbd45ccfa4ed8e8f4":{
      "scriptId":"u145"},
    "b2e2330768444664afcaadbe9f1c1093":{
      "scriptId":"u146"},
    "ec9d62ee2bf541018c00c06a899f497f":{
      "scriptId":"u147"},
    "ed673a4a559e4786b4d856c7feac49ec":{
      "scriptId":"u148"},
    "42d8b8c4fcdd4ccca838b3d37d1b9444":{
      "scriptId":"u149"},
    "ff11073c9c2b458c8eb091049af77795":{
      "scriptId":"u150"},
    "656dcab133e244268b3e62407df936ee":{
      "scriptId":"u151"},
    "737ec7b9996649aebef89c4db9bb248a":{
      "scriptId":"u152"},
    "10d808af721543fcb32f7371bbe55539":{
      "scriptId":"u153"},
    "713a3594cc5c4d26b3721375b9eac9c1":{
      "scriptId":"u154"},
    "cd64f8443cf04e54bfd76570fc8ac40c":{
      "scriptId":"u155"}}});