$axure.loadCurrentPage({
  "url":"扭蛋.html",
  "generationDate":new Date(1477979556434.67),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4fd67ff9bc6644ed8c5017bf8ad3036b",
    "type":"Axure:Page",
    "name":"扭蛋",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d476c9cd7cb74d1bbaa44ea524ce45be",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":20,
              "y":35},
            "size":{
              "width":734,
              "height":1295}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"691cdfc1b5e340eab9a6f1a1f02f2798",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":20,
                  "y":35},
                "size":{
                  "width":734,
                  "height":1295}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u0.png"}},
{
          "id":"d3eb9f29f6c24c1e9b1430bff20f0fa5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":27,
              "y":43},
            "size":{
              "width":720,
              "height":1280}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf6636e0ed0e480da7b62052b263b4df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":27,
                  "y":43},
                "size":{
                  "width":720,
                  "height":1280}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u2.png"}},
{
          "id":"0e5888b2fd074648a52d0e1887cd58ed",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":64,
              "y":1130},
            "size":{
              "width":636,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/付费/u18_line.png"}},
{
          "id":"d04e441efc704f47b06d3e3206db0892",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "opacity":"0.75",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":27,
              "y":43},
            "size":{
              "width":720,
              "height":1280}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff28fae214014dd1bb74ff4240c2adf5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "opacity":"0.75",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":27,
                  "y":43},
                "size":{
                  "width":720,
                  "height":1280}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/副本/u38.png"}},
{
          "id":"52bdda8fb69141aa9c2af9e7683da713",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":628,
              "y":211},
            "size":{
              "width":102,
              "height":98}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0744c0e5ce3c4e8e8b99cf8cc5ce1d76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":628,
                  "y":211},
                "size":{
                  "width":102,
                  "height":98}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主界面",
                      "target":{
                        "targetType":"page",
                        "url":"主界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/副本/u42.png"}},
{
          "id":"d22ee739e469477a992431b6df6b1740",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":207,
              "y":1052},
            "size":{
              "width":350,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"499b60319dbd46d1a76b7c024225c2d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":207,
                  "y":1052},
                "size":{
                  "width":350,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/扭蛋/u9.png"}},
{
          "id":"fdfa8cadfd784ccb8a6778b8aa45b4b2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":326,
              "y":1062},
            "size":{
              "width":51,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2b9e3af1c1244509546623a58da8882",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":326,
                  "y":1062},
                "size":{
                  "width":51,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u22.png"}},
{
          "id":"6f8760ba0c4a474ab7a1f215b4afd003",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":377,
              "y":1072},
            "size":{
              "width":80,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76716781c6904e37877c486f46f9539e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":377,
                  "y":1072},
                "size":{
                  "width":80,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e5057ff65554296944182a77615aac1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":42,
              "y":1130},
            "size":{
              "width":658,
              "height":84}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aefbf485792249d79474ce58a28ec90b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":42,
                  "y":1130},
                "size":{
                  "width":658,
                  "height":84}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/扭蛋/u15.png"}},
{
          "id":"b2eca51d501c4f939ecfb741d2620fe4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":606,
              "y":1103},
            "size":{
              "width":120,
              "height":122}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90dfa4ab086342b1bfed89d1621289ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":606,
                  "y":1103},
                "size":{
                  "width":120,
                  "height":122}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/统计/u123.png"}},
{
          "id":"a954e6572c774ea98f725080365b3c36",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":57,
              "y":1145},
            "size":{
              "width":466,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fc781731f06474392840618dcf17d31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":57,
                  "y":1145},
                "size":{
                  "width":466,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/战斗/u129.png"}},
{
          "id":"c086367de63e43078a133961cb182a13",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":120,
              "y":1145},
            "size":{
              "width":10,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af9b6408d6c34023915c2ebc13a2310a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":120,
                  "y":1145},
                "size":{
                  "width":10,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/扭蛋/u21.png"}},
{
          "id":"edf8a314f79a4a1d844549c229e9b2d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":200,
              "y":1145},
            "size":{
              "width":10,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d88528b7fcbd45b187a6789fa19218d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":200,
                  "y":1145},
                "size":{
                  "width":10,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/扭蛋/u21.png"}},
{
          "id":"bc22b7c58ed24b42b945fb0bb5937724",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":280,
              "y":1145},
            "size":{
              "width":10,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa7c1313c60a49978094a5cc75fd21c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":280,
                  "y":1145},
                "size":{
                  "width":10,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/扭蛋/u21.png"}},
{
          "id":"4abfaace67434c9ab788df1ced86d4a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":360,
              "y":1145},
            "size":{
              "width":10,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70a74335478644bd9f5b1532faed8241",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":360,
                  "y":1145},
                "size":{
                  "width":10,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/扭蛋/u21.png"}},
{
          "id":"dbb029a7e0064ccd9e500e146fe8c3ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":440,
              "y":1145},
            "size":{
              "width":10,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5480e5dad455487aab93363b7781ad1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":440,
                  "y":1145},
                "size":{
                  "width":10,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/扭蛋/u21.png"}},
{
          "id":"650bfc016c0b477b8b7ea81421ac8807",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":520,
              "y":1145},
            "size":{
              "width":10,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9a1e86aea86435095bd446c29294888",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":520,
                  "y":1145},
                "size":{
                  "width":10,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/扭蛋/u21.png"}},
{
          "id":"956e59efb1e24dd6adef873c734a4ce4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":44,
              "y":283},
            "size":{
              "width":687,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43d63e98553d4adc9342a7648b0b1d5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":44,
                  "y":283},
                "size":{
                  "width":687,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/扭蛋/u33.png"}},
{
          "id":"d66e91c5c66345a6a62f8d6709387ba9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":244,
              "y":950},
            "size":{
              "width":276,
              "height":83}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a862257aac5a4d3ebbdbd3a011535b8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":244,
                  "y":950},
                "size":{
                  "width":276,
                  "height":83}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主界面/u6.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "d476c9cd7cb74d1bbaa44ea524ce45be":{
      "scriptId":"u0"},
    "691cdfc1b5e340eab9a6f1a1f02f2798":{
      "scriptId":"u1"},
    "d3eb9f29f6c24c1e9b1430bff20f0fa5":{
      "scriptId":"u2"},
    "cf6636e0ed0e480da7b62052b263b4df":{
      "scriptId":"u3"},
    "0e5888b2fd074648a52d0e1887cd58ed":{
      "scriptId":"u4"},
    "d04e441efc704f47b06d3e3206db0892":{
      "scriptId":"u5"},
    "ff28fae214014dd1bb74ff4240c2adf5":{
      "scriptId":"u6"},
    "52bdda8fb69141aa9c2af9e7683da713":{
      "scriptId":"u7"},
    "0744c0e5ce3c4e8e8b99cf8cc5ce1d76":{
      "scriptId":"u8"},
    "d22ee739e469477a992431b6df6b1740":{
      "scriptId":"u9"},
    "499b60319dbd46d1a76b7c024225c2d9":{
      "scriptId":"u10"},
    "fdfa8cadfd784ccb8a6778b8aa45b4b2":{
      "scriptId":"u11"},
    "f2b9e3af1c1244509546623a58da8882":{
      "scriptId":"u12"},
    "6f8760ba0c4a474ab7a1f215b4afd003":{
      "scriptId":"u13"},
    "76716781c6904e37877c486f46f9539e":{
      "scriptId":"u14"},
    "8e5057ff65554296944182a77615aac1":{
      "scriptId":"u15"},
    "aefbf485792249d79474ce58a28ec90b":{
      "scriptId":"u16"},
    "b2eca51d501c4f939ecfb741d2620fe4":{
      "scriptId":"u17"},
    "90dfa4ab086342b1bfed89d1621289ed":{
      "scriptId":"u18"},
    "a954e6572c774ea98f725080365b3c36":{
      "scriptId":"u19"},
    "1fc781731f06474392840618dcf17d31":{
      "scriptId":"u20"},
    "c086367de63e43078a133961cb182a13":{
      "scriptId":"u21"},
    "af9b6408d6c34023915c2ebc13a2310a":{
      "scriptId":"u22"},
    "edf8a314f79a4a1d844549c229e9b2d9":{
      "scriptId":"u23"},
    "d88528b7fcbd45b187a6789fa19218d5":{
      "scriptId":"u24"},
    "bc22b7c58ed24b42b945fb0bb5937724":{
      "scriptId":"u25"},
    "fa7c1313c60a49978094a5cc75fd21c2":{
      "scriptId":"u26"},
    "4abfaace67434c9ab788df1ced86d4a8":{
      "scriptId":"u27"},
    "70a74335478644bd9f5b1532faed8241":{
      "scriptId":"u28"},
    "dbb029a7e0064ccd9e500e146fe8c3ba":{
      "scriptId":"u29"},
    "5480e5dad455487aab93363b7781ad1d":{
      "scriptId":"u30"},
    "650bfc016c0b477b8b7ea81421ac8807":{
      "scriptId":"u31"},
    "a9a1e86aea86435095bd446c29294888":{
      "scriptId":"u32"},
    "956e59efb1e24dd6adef873c734a4ce4":{
      "scriptId":"u33"},
    "43d63e98553d4adc9342a7648b0b1d5d":{
      "scriptId":"u34"},
    "d66e91c5c66345a6a62f8d6709387ba9":{
      "scriptId":"u35"},
    "a862257aac5a4d3ebbdbd3a011535b8b":{
      "scriptId":"u36"}}});